### ISSUE TITLE
leftview below navigation bar

### ISSUE THREAD

**Issue by safecase123** [Friend-LGA/LGSideMenuController#1]
Thanks for sharing great library. Its amazing.

But I want like leftview below navigation bar.

Can you help me on this.

**Comment by Friend-LGA** [comment]
I think it's not too easy... You can try to make it in this way:
- Create custom UINavigationBar 
- Add it like subview for LGSideViewController.view

I didn't try, but it suppose to be on top of everything

**Comment by safecase123** [comment]
Its working fine with above solution
