### ISSUE TITLE
I can't use module name to resolve conflicts

### ISSUE THREAD

**Issue by danielCarlosCE** [Friend-LGA/LGSideMenuController#103]
```
let segue: LGSideMenuController.LGSideMenuSegue

```
Why that doesn't work?

**Comment by Friend-LGA** [comment]
My be it should be like this?
```swift
let segue: LGSideMenuSegue
```

**Comment by danielCarlosCE** [comment]
I'm using R.swift and it's uses its script to generated properties from the storyboard. The only way it can differ from other modules is using Module prefix. 
It works with other custom segues from other libraries in my project, but it doesn't with LGSideMenu
