### ISSUE TITLE
interactivePopGestureRecognizer does not always work correctly when swiping

### ISSUE THREAD

**Issue by ccampbell** [Friend-LGA/LGSideMenuController#106]
I have noticed that swiping works correctly to go back if you swipe from the side of the view itself, but if you swipe from the side of the navigation bar, it brings up the menu. I think this should also go back to the previous view on the navigation stack.

See GIF:

![swipebug](https://cloud.githubusercontent.com/assets/259316/26604807/8df3b366-4559-11e7-8c64-228b9d6487a8.gif)

**Comment by ccampbell** [comment]
Just wanted to add that this happens not just when swiping from the navigation bar. There are a few pixels that will bring up the menu instead of going back:

![swipebug2](https://cloud.githubusercontent.com/assets/259316/26615226/64b32e34-4593-11e7-9f2b-86c9ffb46a3d.gif)

**Comment by GTMYang** [comment]
我碰到同样的问题，有办法解决么？

**Comment by UninhibitedSoul** [comment]
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    self.sideMenuController.leftViewSwipeGestureEnabled = NO;
}
