### ISSUE TITLE
TableView Swipe to delete not working

### ISSUE THREAD

**Issue by pinkal** [Friend-LGA/LGSideMenuController#109]
In my app i am not using right menu view so i disabled _rightViewSwipeGestureEnabled = NO but it's not allow tableview to swipe. And if i enable _rightViewSwipeGestureEnabled = YES then right menu view will appear (as default functionality).
So how to disable only right menu view and allow tableview to swipe?

Thanks.

**Comment by balkarov** [comment]
I have the same problem.
Did you solved this problem?

**Comment by Friend-LGA** [comment]
Please, take a look at Demo projects, they have a demo case with exactly this situation.
