### ISSUE TITLE
leftViewWidth in LGSideMenuPresentationStyleSlideAbove not working

### ISSUE THREAD

**Issue by koollhimanshu** [Friend-LGA/LGSideMenuController#111]
`self.objSlideOutMenuController = [LGSideMenuController sideMenuControllerWithRootViewController:self.navCenterController];`
    `self.objSlideOutMenuController.leftViewController = self.objLeftMenu;`
   ` _objSlideOutMenuController.leftViewWidth = 250;`
    `_objSlideOutMenuController.leftViewPresentationStyle = LGSideMenuPresentationStyleSlideAbove;`
    
   ` [self.navigationController pushViewController:self.objSlideOutMenuController animated:YES];`

**Comment by Friend-LGA** [comment]
Take a look at demo projects, they do have examples how to set this up.
