### ISSUE TITLE
Cool Slide menu, suggest remove 'IBAction' on UIViewController+LGSideMenuController.h

### ISSUE THREAD

**Issue by xuhanqiang** [Friend-LGA/LGSideMenuController#113]
There are too many 'IBAction' on this category, which cause too many unusable 'IBAction' for an normal viewcontroller's xib. How can i fix this issue？
<img width="527" alt="ibaction" src="https://user-images.githubusercontent.com/12390629/28101297-3b73311c-66fa-11e7-9aca-cbb978340a71.png">

**Comment by Friend-LGA** [comment]
This is not an issue, you just have many options to choose from. It is how Xcode decided to show them. Send feedback to Apple.
