### ISSUE TITLE
LeftMenu 

### ISSUE THREAD

**Issue by nohraay** [Friend-LGA/LGSideMenuController#119]
I have slide show built with ScrollView in Home page, so when I need to slide the left menu with finger in the slideshow area, the left menu is not sliding. please can you tell me how to fix this issue.

**Comment by yusadogru** [comment]
I also have same problem while use scrollView in home page. I think the scroll view's use of those gestures (gesture conflict scrollView and panGesture). I figured it out. My solution is put **shouldBeRequiredToFailByGestureRecognizer** in **LGSideMenuGesturesHandler** class

```
-(BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldBeRequiredToFailByGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer{
    return YES;
}
```

**Comment by nohraay** [comment]
It's working normally now, Thank you for your support @yusadogru

**Comment by fanyuexiang** [comment]
good job!bro :)

**Comment by Friend-LGA** [comment]
I don't have time to test it now, but you always can use your own delegate for panGesture
```objective-c
@property (strong, nonatomic, readonly, nonnull) UIPanGestureRecognizer *panGesture;
```
