### ISSUE TITLE
GestureRecognizer 

### ISSUE THREAD

**Issue by ghost** [Friend-LGA/LGSideMenuController#12]
UISlider and UITableview swipe to edit was not working on any of the viewcontroller, I have UIgesturedelegate and following delegate method, what may be the reason am I missing any?
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer{
  
  return YES;
  }

**Comment by kirk** [comment]
I was having the same problem. I was able to fix my issue by setting the delegate property on the panGesture. 
https://github.com/Friend-LGA/LGSideMenuController/blob/master/LGSideMenuController/LGSideMenuController.m#L248
`panGesture.delegate = self;`

**Comment by satyzkmr** [comment]
Thanks Kirk, It was working for me but now pangesture to reveal the rightviewcontroller doesn't work.

**Comment by Friend-LGA** [comment]
Now you can use ```viewController.gesturesCancelsTouchesInView = NO;```

**Comment by klauslanza** [comment]
Even after setting gesturesCancelsTouchesInView = NO, I still have problems recognising the slide gesture on a table view cell for showing UIRowAction buttons.
 Any idea?

**Comment by risp** [comment]
I have the same problem. Tried the following options but the swipe gesture on a uitableviewcell doesn't get recognized most of the times.

```
self.gesturesCancelsTouchesInView = NO;
self.leftViewSwipeGestureEnabled = NO;
self.rightViewSwipeGestureEnabled = NO;
```

**Comment by Ponf** [comment]
@Friend-LGA this worked for me, however if I have slider in my UITableViewCell, changing value from left to right triggers left menu opening.

**Comment by klauslanza** [comment]
@Ponf What worked for you? @risp solution?

**Comment by zmian** [comment]
@klauslanza @Ponf @risp I had the same problem. I just submitted pull request #38 to fix this.

**Comment by Ponf** [comment]
@zmian I've made it in a bit simpler way: I have created protocol LGSideMenuViewControllerDelegate and implemented it in my code. And I'm asking in UIGestureRecognizerDelegate if it should be cancelled from delegate:

```
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch {
    if (gestureRecognizer == _panGesture) {
        return [_delegate shouldHandlePanRecognizerTouch:touch];
    }
    return ([touch.view isEqual:_rootViewCoverViewForLeftView] || [touch.view isEqual:_rootViewCoverViewForRightView]);
}
```

**Comment by sanu** [comment]
@Ponf , Could you please help me with your implementation. Would be better if you could commit your changes, and send a pull request.

**Comment by rabehssera** [comment]
Can we include the Pull request #39 in the next release ?

Thanks
