### ISSUE TITLE
Reload left view from main view

### ISSUE THREAD

**Issue by malkabani** [Friend-LGA/LGSideMenuController#121]
Hi
How to reload side menu table view from main view.
There is login cell and when user make login i need to reload table in left menu from main view.

**Comment by iDevelopper** [comment]
LGSideMenuController has a property:

@property (strong, nonatomic, nullable) UIViewController *leftViewController;

**Comment by avinashvaghasiya** [comment]
malkabani  how to reload tableview

**Comment by bejgumshirisha** [comment]
@malkabani  Did u found any solution for reloading the tableview content whenever it is being presented.If so please let us know

**Comment by Friend-LGA** [comment]
You can reload your `tableView` at any time you want, just keep it as a property where it is needed for you.
