### ISSUE TITLE
How can i use tabbar controller programatically with LGSideMenuController

### ISSUE THREAD

**Issue by manojrohtela** [Friend-LGA/LGSideMenuController#122]

**Comment by black-lotus** [comment]
[Test Side Menu.zip](https://github.com/Friend-LGA/LGSideMenuController/files/1343018/Test.Side.Menu.zip)

You can download my project test if you are working with UITabBarController

**Comment by Friend-LGA** [comment]
This should be working just fine as any other UIViewControllers. Logic should be the same.
Please give more details, or just look at UITabBarController documentation - https://developer.apple.com/documentation/uikit/uitabbarcontroller
