### ISSUE TITLE
Optional rootviewController

### ISSUE THREAD

**Issue by rahulbbit** [Friend-LGA/LGSideMenuController#123]
Can i set optional rootViewController, from storyboard segue?
 
I want to choose root view according to some response. is that possible?

![screen shot 2017-08-28 at 4 27 11 pm](https://user-images.githubusercontent.com/11924067/29770674-c905afe0-8c0d-11e7-9fc3-834e476c8bb2.png)

**Comment by rahulbandal** [comment]
Same issue how to set option for multiple rootviewcontroller

**Comment by Friend-LGA** [comment]
If you need to wait for some response, then you should assign rootViewController outside of Storyboard.
Like `self.sideMenuController.rootViewController = newRootViewController;`
