### ISSUE TITLE
Weird happenings

### ISSUE THREAD

**Issue by chanonly123** [Friend-LGA/LGSideMenuController#129]
![screen shot 2017-10-24 at 7 59 14 pm](https://user-images.githubusercontent.com/13619184/31949058-0487abe4-b8f6-11e7-8d9d-9a3bfc14176c.png)

In view hierarchy, left menu is visible but in simulator it is not.
and UITextEffectsWindow is added in the view hierarchy! how to remove that?

**Comment by abdbinrus93** [comment]
Hi chanonly123, I have the same bar button on the left

**Comment by abdbinrus93** [comment]
On iphone 6s Plus, It is showing the button very small. What's worse is it is not at the left edge.

**Comment by Friend-LGA** [comment]
`UITextEffectsWindow` probably added by the iOS itself.
Needs more description of the issue. Feel free to reopen.
