### ISSUE TITLE
disable left view completely?

### ISSUE THREAD

**Issue by NoctizJ** [Friend-LGA/LGSideMenuController#130]
Hi, First I wanna say good job making this.
However I didn't find a good doc for this.

I only want right side view. In the setup I set self.leftViewEnabled = NO;
I am using storyboard. It spits exception at 
[self performSegueWithIdentifier:LGSideMenuSegueLeftIdentifier sender:nil];

Do I have to set a segue for left view? How do I disable left view, since I don't need it.

**Comment by iDevelopper** [comment]
If you don't want a left view controller don't create it. And delete the exception breakpoint, if you don't want the app to break.

**Comment by danielCarlosCE** [comment]
+1

**Comment by danielCarlosCE** [comment]
The problem is the code checks the existence this way: 
```
@try {
  [self performSegueWithIdentifier:LGSideMenuSegueLeftIdentifier sender:nil];
}
```

So, if you don't have leftView, it will always throw an exception.

**Comment by danielCarlosCE** [comment]
@NoctizJ one way is actually creating a left segue and select the option to disable left menu. that's far from a good solution, but it stops the problem

**Comment by Friend-LGA** [comment]
Should be fixed in the new version. Please validate.
Feel free to reopen if the issue is still reproducible.
