### ISSUE TITLE
navigation Bar button is too small and it is not at the left edge

### ISSUE THREAD

**Issue by abdbinrus93** [Friend-LGA/LGSideMenuController#133]
I am using LGSideMenuController as it is written in the guide. The problem is the navigation bar buttons look too small. And they are not stuck to the edges of the navigation bar. I have image assets of 64 x 64, 127x 127, 191 x 191. But testing on iPhone 6s Plus they look too small

**Comment by Friend-LGA** [comment]
UINavigationBar is not a part of LGSideMenuController framework. You should google how to change settings of UINavigationBar.
