### ISSUE TITLE
NavigationBar

### ISSUE THREAD

**Issue by Pedrosantos0172** [Friend-LGA/LGSideMenuController#136]
Hi, first of all congrats on the awesome job.
I implemented this in my project with two side menu left side as scaleFromBig and right side as slideAbove.
I'm trying to figure how to show the right side behind the navigation bar.
Can you help me with this??
Thanks

**Comment by Friend-LGA** [comment]
Please, take a look at Demo Projects. They now have a demo case for this situation.
`Usage` -> `Inside UINavigationController`
