### ISSUE TITLE
preferredStatusBarStyle not call when push view if swipe left menu not completed 

### ISSUE THREAD

**Issue by qhu91it** [Friend-LGA/LGSideMenuController#137]
I set status bar for specific view controller, main view is light but child is black, when I swipe left menu a little and swipe close immediately, I push to child view and method preferredStatusBarStyle not called, my status bar not change.
Please help me, thanks.

**Comment by qhu91it** [comment]
It work when I merge this pull
https://github.com/Friend-LGA/LGSideMenuController/pull/112

**Comment by om-ha** [comment]
thanks for pointing out the fix
