### ISSUE TITLE
UISplitViewController

### ISSUE THREAD

**Issue by avjiang** [Friend-LGA/LGSideMenuController#138]
Is there any chance to use this library to display side menu on a UISplitViewController project? 
If so, is there any example or other way around to achieve this using this library? this library is so amazing and helpful to me. Hope somebody can lighten me up :)

Thanks!

**Comment by Friend-LGA** [comment]
Depends on your needs. You have 2 options:
1. Add your UISplitViewController as the rootViewController inside LGSideMenuController
2. Use LGSideMenuController instead of UISplitViewController, and set `alwaysVisibleOptions` to always show side menu when it is needed.
