### ISSUE TITLE
How to round root view controller corner radius through pod?

### ISSUE THREAD

**Issue by rockfarwell** [Friend-LGA/LGSideMenuController#139]
In your test rounded corner branch i see rootViewLayerCornerRadius property, but in the pod installed by podfile it's not exist. Are there any way to use it through pod ?

**Comment by febinfathah** [comment]
Use delegate methods sidemenuwillshow and willhide methods to set and reset corner radios

**Comment by Friend-LGA** [comment]
Yes, you can try to animate corners radius using notifications of `LGSideMenuController`:
```
Notification.showAnimationsForLeftView
Notification.hideAnimationsForLeftView
``` 
Or using callbacks of `LGSideMenuController`:
```
showAnimationsForLeftView: AnimationsCallback?
hideAnimationsForLeftView: AnimationsCallback?
```
Or using delegate `LGSideMenuDelegate`:
```
func showAnimationsForLeftView(sideMenuController: LGSideMenuController,
                                   duration: TimeInterval,
                                   timingFunction: CAMediaTimingFunction)

func hideAnimationsForLeftView(sideMenuController: LGSideMenuController,
                                   duration: TimeInterval,
                                   timingFunction: CAMediaTimingFunction)
```
But, probably, it will be too heavy from performance perspective. 

Also you can do it without actually animating it with `didShowLeftView` and `didHideLeftView`, but I don't think it will look pretty.

Currently LGSideMenuController doesn't support rounded corners natively, and unlikely support will be added in near future.
But you always can implement it on your side using techniques explained above.
