### ISSUE TITLE
Slide Below Presentation Style not Working

### ISSUE THREAD

**Issue by Chr1sK** [Friend-LGA/LGSideMenuController#141]
Hi guys, 

I have implemented this pod successfully to my project and in general everything works fine except a few things (ie new ios11 navigation bar showing over the left menu). The problem i am facing, is that i have set the 'Slide Below' as the presentation style right before i display the left menu, but it's not working. My code is as follows:
        sideMenuController?.leftViewPresentationStyle = .slideBelow
I haven't selected a presentation style from the attribute editor. 

What could i be doing wrong? Any help would be much appreciated

Thanks

**Comment by Friend-LGA** [comment]
You should put UINavigationController inside LGSideMenuController as RootViewController, not the otherwise
