### ISSUE TITLE
在iPhone X上有bug

### ISSUE THREAD

**Issue by OCer** [Friend-LGA/LGSideMenuController#142]
使用左侧滑动，在用滑动来关闭控制器的时候，主控制器上下被剪裁

**Comment by OCer** [comment]
<img width="430" alt="2017-12-21 18 05 58" src="https://user-images.githubusercontent.com/13308894/34251056-bfd1a02a-e679-11e7-9161-d7465e0401aa.png">
<img width="431" alt="2017-12-21 18 06 36" src="https://user-images.githubusercontent.com/13308894/34251312-ad3e3ddc-e67a-11e7-8149-64cfed9fced2.png">

**Comment by OCer** [comment]
解决了

**Comment by xdxavier** [comment]
怎樣解決，我都遇到相同問題
