### ISSUE TITLE
XCode 9: This block declaration is not a prototype

### ISSUE THREAD

**Issue by shadowsheep1** [Friend-LGA/LGSideMenuController#143]
XCode 9 warns about semantic issues in this situation:

https://stackoverflow.com/questions/44473146/this-function-declaration-is-not-a-prototype-warning-in-xcode-9

Just so we know that.

**Comment by chrisvoronin** [comment]
got the same fix, can push, but I think I need to be added to project.

**Comment by alkharaz** [comment]
its not fixed

**Comment by anastasioscho** [comment]
@alkharaz try this in your Podfile:
pod 'LGSideMenuController', :git => 'https://github.com/Friend-LGA/LGSideMenuController', :branch => 'master'
Correct me if i am wrong but at the time of this writing we have to specify explicitly the master branch to get the latest commits.

**Comment by alkharaz** [comment]
Thats solve it

thanks

**Comment by Friend-LGA** [comment]
Fixed
