### ISSUE TITLE
Integrate Login Screen before launching sideview controller

### ISSUE THREAD

**Issue by mokshaharish** [Friend-LGA/LGSideMenuController#146]
Hi,

I'm trying to add login screen before launching LGSideMenuViewController and a logout screen after session timeout. Can someone pls help how to add Login screen and Logout.
Right now the root view controller is changing and unable to reach the required controller.
Appreciate your help!

Thanks,
MH

**Comment by mokshaharish** [comment]
@Friend-LGA  Any updates for my question. Appreciate your help.

Thanks,
MH

**Comment by Friend-LGA** [comment]
You have 2 options:
1. Show login screen before showing sideMenuController
2. Show login screen as the rootView inside sideMenuController

Feel free to implement this in any way you like
