### ISSUE TITLE
LGSideMenuDelegate  when use  AppDelegate.delegate.navigationController?.isNavigationBarHidden = true;  some time implement the delegate willShow,didShow and the side menu not show  

### ISSUE THREAD

**Issue by salah-mohammed** [Friend-LGA/LGSideMenuController#148]
LGSideMenuDelegate

when use  AppDelegate.delegate.navigationController?.isNavigationBarHidden = true; 
some time implement the delegate willShow,didShow and the side menu not show

**Comment by Friend-LGA** [comment]
Needs more detailed description.
