### ISSUE TITLE
app get crash when click on side menu

### ISSUE THREAD

**Issue by umairqureshi6** [Friend-LGA/LGSideMenuController#149]
i have implemented using the example
app get crashed on        
`self.rootViewCoverView.backgroundColor = self.rootViewCoverColorForLeftView;` 
 in class LGSideMenuController

after commenting these lines, the app is working fine but side menu is transparent

can you please help, why its getting crash?

**Comment by Friend-LGA** [comment]
Don't use `self.rootViewCoverView` directly. You should specify `self.rootViewCoverColorForLeftView` and it will set automatically when needed.
