### ISSUE TITLE
How to disable

### ISSUE THREAD

**Issue by Bashta** [Friend-LGA/LGSideMenuController#15]
How to hide this view In certain ViewControllers that are embedded under the same navigation controller?

**Comment by Friend-LGA** [comment]
```objective-c
leftViewSwipeGestureEnabled = NO;
rightViewSwipeGestureEnabled = NO;
```
And hide any buttons that can show it.

**Comment by Bashta** [comment]
Hey, already solved this problem but thank you for the response. By the way found a bug with custom UIControls. The gesture recogniser set cancels the touches to the controls. The solution i used to  resolve the problem was to set 
```
tapGesture.cancelsTouchesInView = NO;
panGesture.cancelsTouchesInView = NO;
```
 Could you please update the the repo so i can return using pods instead of importing it as a 3rd part Framework

**Comment by Friend-LGA** [comment]
Thanks, in a few days I will update this repo with additional some fixes :)

**Comment by Friend-LGA** [comment]
Now you can use ```viewController.cancelsTouchesInView = NO;```

**Comment by Bashta** [comment]
Cheers!
