### ISSUE TITLE
How to reload tableview in left sidemenu

### ISSUE THREAD

**Issue by ChintanWeapp** [Friend-LGA/LGSideMenuController#153]
I have different dynamic data to display in tableview of left menu. How can I achieve this?

**Comment by ChintanWeapp** [comment]
Solved by my self by setting delegate to LGSideMenuController and reloading tableview in leftmenu controller by sending notification using NSNotificationCenter

**Comment by RuchiMakadia** [comment]
also, work for me using NSNotificationCenter
