### ISSUE TITLE
left View Always Visible on iPad/iPhone RTL 

### ISSUE THREAD

**Issue by oenama** [Friend-LGA/LGSideMenuController#157]
hi @Friend-LGA 
I'm using LGSideMenuController with splitViewController and set left View Always Visible on iPad, everything is good for the LTR , but when I started localizing the app to RTL, a weird space between master and details view showed up and I believe it has the same width for the side menu. 

**here is the normal one for LTR view (side menu always visible + uisplitViewController) :** 

![simulator screen shot - ipad pro 9 7-inch - 2018-06-07 at 11 08 32](https://user-images.githubusercontent.com/11976534/41093250-89b637e0-6a53-11e8-83c4-72763ff4bd1e.png)

**and here's for RTL and the weird space :** 

![simulator screen shot - ipad pro 9 7-inch - 2018-06-07 at 11 15 08](https://user-images.githubusercontent.com/11976534/41093286-9789db42-6a53-11e8-8b0d-90d4db7c12d0.png)

 when I change the settings for  LGSideMenuController and disable the alwaysVisible option it seems normal without the space or anything.

I also tried to change the side menu and used the right menu for RTL but its the same. 

here's what I used for  LGSideMenuController  : 

   `let navigationController = UINavigationController(rootViewController: viewController)
        
        let sideMenuController = LGSideMenuController(rootViewController: navigationController)
             sideMenuController.leftViewController = leftMenu
            
            sideMenuController.leftViewWidth = 100.0;
            sideMenuController.leftViewPresentationStyle = .slideAbove
            
             sideMenuController.leftViewLayerShadowColor = UIColor(red:0.96, green:0.96, blue:0.96, alpha:1.00)
            sideMenuController.leftViewLayerShadowRadius = 4
            sideMenuController.leftViewAlwaysVisibleOptions = [.onPad]`

 any help? @Friend-LGA 
thank you.

**Comment by AhmedShammala** [comment]
+1

**Comment by Friend-LGA** [comment]
I've just tested it on latest master and it seems to work just fine. So should be fixed now. Please, validate.
Feel free to reopen if issue is still reproducible.
