### ISSUE TITLE
Number of Warnings in Xcode 11

### ISSUE THREAD

**Issue by ethanwa** [Friend-LGA/LGSideMenuController#158]
Has anyone looked into fixing the `This block declaration is not a prototype` warnings on Xcode 9.4?

**Comment by lotfyahmed** [comment]
Why are there 5 warnings in Swift 4 project? 
You should fix them ASAP.

**Comment by ilTrev** [comment]
As far as I know, this issue could be easily fixed by replacing the three occurrences of "()" with "(void)".
I'd be happy to contribute by branching and issuing a pull request, but it's in my understanding that I need to be part of the project before I can contribute to it

**Comment by RJ-Clegg** [comment]
Any update on this?

**Comment by ilTrev** [comment]
> Any update on this?

Currently the only workaround is this
https://github.com/Friend-LGA/LGSideMenuController/issues/143#issuecomment-390436293

**Comment by jaydip369** [comment]
No...

**Comment by purepure** [comment]
any one works on this repo since it is the best sidemenu for ios, I really thank those dude work and want this issue fixed!
BR

**Comment by ethanwa** [comment]
STILL an issue. I hope this project hasn't been abandoned.

<img width="434" alt="Screen Shot 2019-09-13 at 10 39 26 PM" src="https://user-images.githubusercontent.com/1653780/64902590-18ae3380-d678-11e9-8e74-4886fa484d41.png">

**Comment by Friend-LGA** [comment]
Fixed
