### ISSUE TITLE
Left side menu cant be seen on right on right to left languages

### ISSUE THREAD

**Issue by kaannesinn** [Friend-LGA/LGSideMenuController#159]
Hi,

When I change device language to a rtl language (ie Arabic, etc) left side menu is not on right side automatically. Left and right side menus have to be swapped I think in this case. Is it normal because left bar button is seen on the right but when we click it is shown from left again.

For doing this, I have to swap segues on storyboard or change programmatically by setting left to right and right to left vc.

Thanks

**Comment by SQTDhaval** [comment]
@kaannesinn you can try below code in appDelegate file

if MyUserDefault.getLaunguageCode() == UtilString.LanguageEnglish
        {
            self.lgSideMenuObj.leftViewController = self.sideMenuObj
            self.lgSideMenuObj.leftViewWidth = 250.0
            self.lgSideMenuObj.rootViewScaleForLeftView = 0.651
            self.lgSideMenuObj.leftViewPresentationStyle = LGSideMenuPresentationStyle(rawValue: 0)!
            self.lgSideMenuObj.isLeftViewSwipeGestureEnabled = false
            self.window?.rootViewController = self.lgSideMenuObj
            self.window?.makeKeyAndVisible()
        }
        else{
            self.lgSideMenuObj.rightViewController = self.sideMenuObj
            self.lgSideMenuObj.rightViewWidth = 250.0
            self.lgSideMenuObj.rootViewScaleForRightView = 0.651
            self.lgSideMenuObj.rightViewPresentationStyle = LGSideMenuPresentationStyle(rawValue: 0)!
            self.lgSideMenuObj.isRightViewSwipeGestureEnabled = false
            self.window?.rootViewController = self.lgSideMenuObj
            self.window?.makeKeyAndVisible()
        }

And use it every viewController when use sidemenu button click

@IBAction func BtnSideMenuOnClick(_ sender: Any)
    {
        if MyUserDefault.getLaunguageCode() == UtilString.LanguageEnglish
        {
            let APPDELEGATE = UIApplication.shared.delegate as! AppDelegate
            APPDELEGATE.lgSideMenuObj.showLeftViewAnimated()
        }
        else
        {
            let APPDELEGATE = UIApplication.shared.delegate as! AppDelegate
            APPDELEGATE.lgSideMenuObj.showRightViewAnimated()
        }
    }

**Comment by kaannesinn** [comment]
Thanks @SQTDhaval 👍 I wrote a code like this by swapping the left and right vcs as a short solve. It can also be done by changing leftViewController and rightViewController.

But I thought that it could be handled on LGSideMenuController's codes.

Anyway, thanks again for advice ;) I will close the issue.
