### ISSUE TITLE
kMainViewController

### ISSUE THREAD

**Issue by mikelsoft** [Friend-LGA/LGSideMenuController#16]
My view controller where I want to use kMainViewController is not the root controller. My view controller is located in a tabbarcontroller as root controller and then as subview of a navigation controller . How do I have to change the #define below to make it work?

#define kMainViewController (MainViewController *)[[(AppDelegate *)[[UIApplication sharedApplication] delegate] window] rootViewController]

Thanks in advance Michael

**Comment by Friend-LGA** [comment]
Hello, Michael.

I am not really understand you. kMainViewController used only in demo project as a short link to my main view controller.

In your situation I see two ways:

Wrap your general navigation controller in LGSideMenuController and make it active only on controller that you need.
Just add your custom UIView above everything inside your view controller and make animation like in my LGSideViewController.

**Comment by mikelsoft** [comment]
Thanks Grigory I will have a look into it again !
