### ISSUE TITLE
Inconsistency between pod and repository?

### ISSUE THREAD

**Issue by ilTrev** [Friend-LGA/LGSideMenuController#160]
While building a project including the pod, I am receiving three warnings about block declarations not being prototypes in LGSideMenuController.h, LGSideMenuHelper.h and LGSideMenuView.h.

Since the solution would be quite easy to implement, I cloned the repository to create a branch and do that on my own, but I see that the master branch of the repo does not match the pod.
Specifically, these three warnings have already been fixed, even if the version (2.1.1) appears to be the same both in pod and repository.

Am I missing something? Anything I could do to fix the issue (apart from manually importing the framework)?

The incriminated lines of code are:

LGSideMenuController.h:
(pod)
`typedef void (^ _Nullable LGSideMenuCompletionHandler)();`
(master)
`typedef void (^ _Nullable LGSideMenuCompletionHandler)(void);`

LGSideMenuHelper.h:
(pod)
`+ (void)animateWithDuration:(NSTimeInterval)duration
                 animations:(void(^)())animations
                 completion:(void(^)(BOOL finished))completion;`
(master)
`+ (void)animateWithDuration:(NSTimeInterval)duration
                 animations:(void(^)(void))animations
                 completion:(void(^)(BOOL finished))completion;`

LGSideMenuView.h:
(pod)
`- (nonnull instancetype)initWithLayoutSubviewsHandler:(void(^ _Nonnull)())layoutSubviewsHandler;`
(master)
`- (nonnull instancetype)initWithLayoutSubviewsHandler:(void(^ _Nonnull)(void))layoutSubviewsHandler;`

**Comment by ilTrev** [comment]
Ok, I just got it and it makes sense: the fix was applied in commit bf193b2 and merged in 7aa3232, but no version bump and tag were applied.
Any chance this can be done by someone?

**Comment by ethanwa** [comment]
Really hoping someone can do this soon.

**Comment by Friend-LGA** [comment]
Done
