### ISSUE TITLE
Top constraint break inside scrollview when open keyboard and open navigation menu

### ISSUE THREAD

**Issue by khimani91** [Friend-LGA/LGSideMenuController#161]
Hi,

I have fetch one issue in this project. When I have type something in UITextField and which in inside UIScrollView on ViewController that time keyboard is open and without close keyboard and open navigation drawer "UIScrollView move up with 20 pt(status bar height) up". Any possible solutions or alternate is height appreciated.

Thanks.

**Comment by Friend-LGA** [comment]
I don't think it is related to this Framework. Does the issue only occur when your scroll view is added as the root view?
Feel free to reopen if it is really related to LGSideMenuController itself.
