### ISSUE TITLE
Section Footer text overlaps with cell content on 4 inch screen

### ISSUE THREAD

**Issue by Double-Dude** [Friend-LGA/LGSideMenuController#162]
<img width="475" alt="screen shot 2018-08-07 at 5 28 54 pm" src="https://user-images.githubusercontent.com/12950464/43756247-d5bb9e02-9a67-11e8-8cc0-e72a230017f7.png">

**Comment by Friend-LGA** [comment]
I don't think it is related to this Framework. Does the issue only occur when table view is added to one of the side views?
Feel free to reopen if it is really related to LGSideMenuController itself.
