### ISSUE TITLE
Reload the left view table

### ISSUE THREAD

**Issue by reenaphilip** [Friend-LGA/LGSideMenuController#164]
Is it possible to reload the tableview in left menu view controller whenever open the left view ?

**Comment by RuchiMakadia** [comment]
I also have same issue, I want to reload the right menu's table view. please help thank in advance

**Comment by bejgumshirisha** [comment]
I want to reload the left menu table data.If you find any solution please post it.

**Comment by iVikramChaudhary** [comment]
I also faced the same issue but I fixed by using NotificationCenter in LeftMenuVC

**Comment by iDevelopper** [comment]
Why do not use the delegate method?
```swift
    func willShowLeftView(_ leftView: UIView, sideMenuController: LGSideMenuController) {
        if let leftVC = sideMenuController.leftViewController as? LeftViewController {
            leftVC.tableView.reloadData()
        }
    }
```

**Comment by Friend-LGA** [comment]
You can use one out of three options:
1. Set the callback `sideMenuController.willShowLeftView()`
2. Set the delagate method `delegate.willShowLeftView()`
3. Use `NSNotificationCenter` and `addObserver` for key `LGSideMenuWillShowLeftViewNotification `
