### ISSUE TITLE
Tabbar with sidemenu

### ISSUE THREAD

**Issue by farazhaider88** [Friend-LGA/LGSideMenuController#165]
I want to use tabbar with sidemenu and tabbar containing navigation, is there any Swift example containing this implementation, also is each tabbar view should be inherited from sidemenu to have sidemenu effect.

**Comment by jahnaviredspark** [comment]
I have faced some issue

**Comment by NikhilManapure** [comment]
any example?

**Comment by Friend-LGA** [comment]
You don't need to inherit `UITabBarController` from `LGSideMenuController`. You just need to make `LGSideMenuController` as your window's root controller, and make `UITabBarController` as a root controller for `LGSideMenuController`

Like this:
```swift
let tabBarController = UITabBarController()
let sideMenuController = LGSideMenuController()
sideMenuController.rootViewController = tabBarController
window.rootViewController = sideMenuController
```

**Comment by Friend-LGA** [comment]
I've added a few examples in Demo projects. Check `Usage` section:
- As Container for UITabBarController
- Inside UITabBarController

**Comment by ahmedayoub95** [comment]
Hy Faraz did you solved this issue?
