### ISSUE TITLE
UIPanGestureRecognizer case UIButton event fail.

### ISSUE THREAD

**Issue by bryanluo** [Friend-LGA/LGSideMenuController#17]
The pan gesture recognizer case  UIButton can't receive UIControlEventTouchDragExit and UIControlEventTouchDragEnter event actions.

I suggest set the cancelsTouchesInView  to NO.     panGesture.cancelsTouchesInView = NO;

**Comment by Friend-LGA** [comment]
Now you can use ```viewController.cancelsTouchesInView = NO;```
