### ISSUE TITLE
Please add support for Swift Package Manager (Dependencies)

### ISSUE THREAD

**Issue by ethanwa** [Friend-LGA/LGSideMenuController#172]
Many people will be moving away from CocoaPods and Carthage and using Swift Package Manager (Dependencies). Can you please add support? Thank you!

**Comment by ethanwa** [comment]
Xcode 12 and Swift 5.3 (both available as dev betas) now include resource and closed-source binary support for SPM. Hopefully SPM can now be done for this?

https://www.hackingwithswift.com/articles/218/whats-new-in-swift-5-3

**Comment by ethanwa** [comment]
Xcode 12 is now GM. Would love to see SPM support now. This is one of my remaining Pods that has yet to move to SPM.

**Comment by Friend-LGA** [comment]
Thank you for pointing this. Support has been added - https://github.com/Friend-LGA/LGSideMenuController/commit/cb4a1c85f70e1f28b9736cfa8f1cb4d863ffe7dd
Now you can add LGSideMenuController as Swift Package starting with version 2.3.0

**Comment by ethanwa** [comment]
Hi, this doesn't appear to be working properly. When I add the Swift Package to a fresh clean project and build, I am getting the error: 

`module LGSideMenuController {
umbrella "/Users/ethanallen/Library/Developer/Xcode/DerivedData/test-hcrghhrnydusfbebtnedhzkvymfv/SourcePackages/checkouts/LGSideMenuController/LGSideMenuController/include"
export *
}`

There is no "include" folder. And when I add `LGSideMenuDelegate` I am getting errors as well.
