### ISSUE TITLE
Not Show full screen side menu

### ISSUE THREAD

**Issue by jaag12** [Friend-LGA/LGSideMenuController#173]
Hello before you thank the work done in the library. My side menu is not shown in full screen is cut to the height of the main menu, what am I doing wrong ?. My configuration is this:

`SideMainVC *sideMainController=[[SideMainVC alloc] initWithNibName:@"SideMain" bundle:nil];
  
        MainPrincipalVC *mainPrincipal = [[MainPrincipalVC alloc] init];

  
    
    LGSideMenuController *sideMenuController = [LGSideMenuController sideMenuControllerWithRootViewController:mainPrincipal
                                                                                           leftViewController:sideMainController
                                                                                          rightViewController:nil];
    sideMenuController.leftViewWidth = 250.0;
    sideMenuController.leftViewPresentationStyle = LGSideMenuPresentationStyleScaleFromBig;
    sideMenuController.leftViewBackgroundBlurEffect = [UIBlurEffect effectWithStyle:UIBlurEffectStyleRegular];`

Thanks you

**Comment by asheesh5391** [comment]
Hey I am facing the same issue. Have you got the fix?

**Comment by asheesh5391** [comment]
Hey You can use

        `lgSideMenuVC.modalPresentationStyle = .currentContext`

**Comment by Friend-LGA** [comment]
Take a look at demo projects. they have good examples of how to setup everything.
