### ISSUE TITLE
Nav bar appears under notch on iPhone X, 11 Pro

### ISSUE THREAD

**Issue by CMoebius** [Friend-LGA/LGSideMenuController#174]
I am having a problem with our rollout of iOS 13 changes and I have been running on devices with a notch (iPhone X & iPhone 11 Pro). The nav bar in our app is appearing under the notch on those devices, so I looked at the demo app and found it doing the same thing. Is there an issue with LGSideMenu for devices with a notch or is the demo and our app not doing something that it needs to to account for the notch?

**Comment by CMoebius** [comment]
To be clear, the problem occurs when selecting an item from the left menu to display the new controller "full-screen". That's when the nav bar appears under the notch. It appears that the method LGSideMenu uses to present the new view controller is not doing something it shouldn't.

**Comment by CMoebius** [comment]
Another piece of information: when I use LGSideMenuPresentationStyleScaleFromBig or LGSideMenuPresentationStyleScaleFromLittle this anomaly happens. When I use LGSideMenuPresentationStyleSlideAbove or LGSideMenuPresentationStyleSlideBelow the nav bar is not under the notch.

**Comment by iamsanketray123** [comment]
Facing same issue after iOS 13... any fix?

**Comment by iamsanketray123** [comment]
facing the same issue...any fix?

**Comment by Friend-LGA** [comment]
Should be fixed now.
Fell free to reopen if the issue is still actual.
