### ISSUE TITLE
Infinite loop when we reload leftmenu tableview

### ISSUE THREAD

**Issue by bejgumshirisha** [Friend-LGA/LGSideMenuController#175]
To reload the content in leftside tableview. I added tableview reload in **viewWillLayoutSubviews** method but it it going to infinte loop.Any solution for left menu content reload

**Comment by iDevelopper** [comment]
I don't know the framework but I guess you can achieve that in a delegate method like:

```
- (void)willShowLeftView:(nonnull UIView *)leftView sideMenuController:(nonnull LGSideMenuController *)sideMenuController;
```

**Comment by Friend-LGA** [comment]
It is not a good idea to reload data inside `viewWillLayoutSubviews` method. Inside this method you should update layout of your views. 
You should reload data of your `tableView` only when it is needed for your needs, outside of render pipeline.
