### ISSUE TITLE
Remove Navigation Bar from LeftViewController

### ISSUE THREAD

**Issue by bejgumshirisha** [Friend-LGA/LGSideMenuController#176]
When i show left view I want to hide Navigation Bar.I wrote in sidemenu controllers as well as main controller also in LeftViewcontroller.From no where it is reflecting.

How to remove navigation bar in leftviewcontroller

**Comment by Friend-LGA** [comment]
You have full control over UINavigationController. This framework is just a container for your navigation controller, it doesn't control its behaviour. Just google how to hide UINavigationBar from UINavigationController.
