### ISSUE TITLE
Closed on click

### ISSUE THREAD

**Issue by Zeeshan90** [Friend-LGA/LGSideMenuController#177]
close the side menu when clicked on the row of the table view

**Comment by irfan0786** [comment]
```
MainViewController *mainViewController = (MainViewController *)self.sideMenuController;
[mainViewController hideLeftViewAnimated:YES completionHandler:nil];
```

**Comment by Zeeshan90** [comment]
i have tried but not closed when i move to other viewcontroller. can the view come to front and closed the side menu ?

**Comment by Friend-LGA** [comment]
You should have a link to instance of `LGSideMenuController`, and just call `hideLeftViewAnimated` on this instance.
Closing as not an issue of the framework.
