### ISSUE TITLE
Not working in iOS 13 

### ISSUE THREAD

**Issue by pushpankq** [Friend-LGA/LGSideMenuController#178]

**Comment by VincenzoMan** [comment]
The solution is to implement the same code insert into    "func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {}" in AppDelegate (How sometimes you do in iOS12) into  "func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {}" in SceneDelegate in iOS 13

**Comment by Friend-LGA** [comment]
Should be working. Please, take a look at demo projects.
Feel free to reopen if the issue is still actual.
