### ISSUE TITLE
Trouble with right Menu

### ISSUE THREAD

**Issue by chlebta** [Friend-LGA/LGSideMenuController#18]
When I use : 
>       sideMenuController.leftView().addSubview(menuController.view)

my code works fine but when I use : 

>        sideMenuController.rightView().addSubview(menuController.view)

my app crash and I get this error : 
**fatal error: unexpectedly found nil while unwrapping an Optional value**

**Comment by Friend-LGA** [comment]
Did you use this method before?
```objective-c
- (void)setRightViewEnabledWithWidth:(CGFloat)width
                   presentationStyle:(LGSideMenuPresentationStyle)presentationStyle
                alwaysVisibleOptions:(LGSideMenuAlwaysVisibleOptions)alwaysVisibleOptions;
```

**Comment by chlebta** [comment]
Yep this fixed the error  but the menu view is empty, now I'm using RESideMenu and the menu work's fine, but with `LGSideMenuController` the menu tableview is not shown

**Comment by Friend-LGA** [comment]
I updated demo projects. Check it out, left and right side menus works fine.
If it's not help you, show me more your code.
