### ISSUE TITLE
Gap created when controller on rootview is forcefully swiped with leftViewPresentationStyle as scaleFromBig

### ISSUE THREAD

**Issue by Prashant-Sah** [Friend-LGA/LGSideMenuController#180]
I have set a navigation controller as the rootcontroller a controller with collectionview in it is the root controller of the navigation controller. I have a controller with menu items as LeftController. With leftview open and the presentation style set as ScaleFromBig, I pull the screen up and down on the controller with collectionview. On tapping the leftmenu a gap is created between the navigationbar and the view and the navigation bar moves up. 
I have attached the screenshot.

I'm using Xcode 11.3, Swift-5 and LGSideMenuController (2.1.1)

<img width="298" alt="Screen Shot 2020-06-01 at 13 01 38" src="https://user-images.githubusercontent.com/23719280/83384973-0f344980-a408-11ea-931a-cf258fcf8334.png">

**Comment by Friend-LGA** [comment]
Can you try current master to check if the issue still actual?

**Comment by Friend-LGA** [comment]
Feel free to reopen if the issue is still reproducible.
