### ISSUE TITLE
Update label or view in left view

### ISSUE THREAD

**Issue by FoxPB** [Friend-LGA/LGSideMenuController#181]
I'm in my active HomeViewController and need to change the status of a label or view in left view

I tried to manipulate the viewController of the left view by its viewmodel instantiated in my HomeViewController but I was not successful

Thank you in advance for your attention

**Comment by Friend-LGA** [comment]
Everything inside `RootView`, `LeftView` or `RightView` is your responsibility, this framework just controls locations of these views, not their content. You need to have a link to your label, as a property somewhere, then you will be able to change it at any time you want.
