### ISSUE TITLE
A number of logic errors appear when running Xcode's Analyze utility

### ISSUE THREAD

**Issue by ethanwa** [Friend-LGA/LGSideMenuController#184]
Go to Xcode > Product > Analyze

<img width="413" alt="Screen Shot 2021-02-09 at 12 23 51 AM" src="https://user-images.githubusercontent.com/1653780/107319615-25050e80-6a6d-11eb-9b7b-5a2f705cf4df.png">

**Comment by Friend-LGA** [comment]
Should be fixed now, can you check version 3.0.0?
