### ISSUE TITLE
Warning when adding LGSideMenuController via SPM

### ISSUE THREAD

**Issue by ethanwa** [Friend-LGA/LGSideMenuController#185]
Hi, when I add the Swift Package to a fresh clean project and build, I am getting the Warning: 

`module LGSideMenuController {
umbrella "/Users/ethanallen/Library/Developer/Xcode/DerivedData/test-hcrghhrnydusfbebtnedhzkvymfv/SourcePackages/checkouts/LGSideMenuController/LGSideMenuController/include"
export *
}`

And when I add `LGSideMenuDelegate` I am getting Errors and my project won't build.

_Originally posted by @ethanwa in https://github.com/Friend-LGA/LGSideMenuController/issues/172#issuecomment-774579016_

**Comment by Friend-LGA** [comment]
Should be fixed now, can you check version 3.0.0?
