### ISSUE TITLE
Issue with status bar color starting in version 3.1.0

### ISSUE THREAD

**Issue by ethanwa** [Friend-LGA/LGSideMenuController#186]
Starting in version 3.1.0 I'm seeing the following issue with my status bar color being a lighter color on the left menu view and I don't know how to fix it:

<img width="365" alt="Screen Shot 2021-04-14 at 9 41 40 PM" src="https://user-images.githubusercontent.com/1653780/114981953-c426f780-9e5c-11eb-9a52-4f9e12f2562d.png">

With version 3.0.1 everything was looking correctly like we wanted, as shown here:

<img width="343" alt="Screen Shot 2021-04-16 at 2 39 35 AM" src="https://user-images.githubusercontent.com/1653780/114982104-02241b80-9e5d-11eb-9b22-4ef463a8f372.png">

The one main thing I noticed with the change is the requirement for new protocol stubs.

Any ideas what is going on here?

**Comment by Friend-LGA** [comment]
Yes. It's not a bug, it's a feature :) 
I've added status bar background to make it easier for user to add UITableView and avoid interference between content of table view and content of status bar while scrolling. Not yet sure what the default behaviour should be though.

You can always disable this with:
```swift
isLeftViewStatusBarBackgroundVisible = false
```
or 
```swift
isLeftViewStatusBarBackgroundHidden = true
```

Demo projects have show cases for this and other features. Please, take a look.

**Comment by Friend-LGA** [comment]
> The one main thing I noticed with the change is the requirement for new protocol stubs.

You mean subs for `delegate` object after library was converted from `Objective-C` to `Swift`?
It actually shouldn't require for you to implement empty stubs, as I have them in extension here:
https://github.com/Friend-LGA/LGSideMenuController/blob/master/LGSideMenuController/LGSideMenuDelegate.swift#L94-L128

Or do you mean something else?

Also, if this question is unrelated to the status bar background issue, let's open separate issue and continue the discussion there.
