### ISSUE TITLE
Would you consider adding another beautiful leftViewPresentationStyle?

### ISSUE THREAD

**Issue by waz0820** [Friend-LGA/LGSideMenuController#2]
if, my pleasure. A picture is worth a thousand words.
https://www.dropbox.com/sh/kcvuimjukhpst99/AAA7lIgU-xS-BptQRzgxkg8_a?dl=0

**Comment by Friend-LGA** [comment]
Do you want to make root view blurred? It's not to easy, but you can try to change this property:
```objective-c
controller.rootViewCoverColorForLeftView = [UIColor colorWithWhite:1.f alpha:0.75]
```

**Comment by waz0820** [comment]
Yeah, blur root view, that's what I mean. LGSideMenuController is the most concise code of side menu I've ever seen. I love it.

**Comment by Friend-LGA** [comment]
Thanks for this, but now I don't have enough time. Pull requests are welcome.

**Comment by mohpor** [comment]
in iOS 9 blur animation is added, you can use `UIVisualEffect` to achieve this, but it still would have severe performance impact. What you have tried so far is good enough I think (making a blurred image and changing it according to menu distance), but if you still want to have a better looking effect, try animating blur in iOS 9. I've tried it and my conclusion is that user's device must be equipped with at least A8 to have a smooth effect, other wise you're gonna have a performance around 40 fps (in contrast with standard 60 fps). I can give you a hand if you were interested in this too. Let me know.
Meanwhile, check out this discussion: https://forums.developer.apple.com/thread/4140
Cheers, M.

**Comment by RameshiOS** [comment]
I want to show right view on view controller 2

**Comment by Friend-LGA** [comment]
Blur was added in new version of library. Look at README.md and try demo projects.
