### ISSUE TITLE
Left menu top space

### ISSUE THREAD

**Issue by moto2015** [Friend-LGA/LGSideMenuController#20]
Hi, how to set top space on the left menu to 0?
![photo591605735158294442](https://cloud.githubusercontent.com/assets/10186744/11319712/8efdf364-90b2-11e5-893d-e4b4be3ae4cf.jpg)

**Comment by Friend-LGA** [comment]
Left View is just usual UIView and inside it you can add any view and setup it like you want.
If you will add UITableView inside UIView, it will not have top space by default.
