### ISSUE TITLE
Disable visible for some period

### ISSUE THREAD

**Issue by brightsider** [Friend-LGA/LGSideMenuController#22]
How I can to disable visible of left/right view for some time period?
Example:
- when user in guest mode - disabled right view
- when user on login/register - disable left and right view

**Comment by Friend-LGA** [comment]
Just set 
```objective-c
self.leftViewSwipeGestureEnabled = NO;
self.rightViewSwipeGestureEnabled = NO;
```

**Comment by brightsider** [comment]
It's not comfortable when needs to check all UINavigationController view controllers hierarchy.

**Comment by Friend-LGA** [comment]
Ok, added: https://github.com/Friend-LGA/LGSideMenuController/commit/cda3e47d45a4d0e228e4586fb9c4bd3078a5cea4

**Comment by brightsider** [comment]
@Friend-LGA thanks!
