### ISSUE TITLE
it can't trigger viewcontroller lifecycle

### ISSUE THREAD

**Issue by zwy2937** [Friend-LGA/LGSideMenuController#27]
such as  : when i want to show leftcontroller ,viewwillappear in leftviewcontroller can't trigger!!!

**Comment by dtfiedler** [comment]
I believe this relates to my issue (#33)

**Comment by jgarth** [comment]
@zwy2937 @dtfiedler I just ran into the same problem and solved it by calling the appropriate view controller lifecycle methods `-addChildViewController` and `-didMoveToParentViewController` as used in other container view controllers. They should be called right before & right after the side view is setup.

```
let leftVC = storyboard.instantiateViewController("someIdentifier")!
addChildViewController(leftVC)
        
setLeftViewEnabledWithWidth(250.0, presentationStyle: .SlideAbove, alwaysVisibleOptions: [.OnNone])
leftViewStatusBarVisibleOptions = [.OnAll]
leftView().addSubview(leftVC.tableView)
leftVC.didMoveToParentViewController(self)
```

Now all the lifecycle methods (like `-viewDidAppear`) are called on my left side view controller and the table view works as expected.

**Comment by Friend-LGA** [comment]
Try new version, is it ok now?

**Comment by Friend-LGA** [comment]
Feel free to open issue back if you have more questions.

**Comment by black-lotus** [comment]
I have same issue even using latest version of LGSideMenuController
viewWillAppear won't executed after re-open left menu

**Comment by iDevelopper** [comment]
This function is called even if you do not open the menu, just twice and not after. I tested the function delegate: func willShowLeftView (_ leftView: UIView, sideMenuController: LGSideMenuController): not called.

```
class MainViewController: LGSideMenuController, LGSideMenuDelegate {
// ...
            self.delegate = self
// ...

```
```
    func willShowLeftView(_ leftView: UIView, sideMenuController: LGSideMenuController) {
        print("Will Show Left View")
    }
```
