### ISSUE TITLE
Not rotating on iPad2

### ISSUE THREAD

**Issue by gurhub** [Friend-LGA/LGSideMenuController#29]
When menu is opened iPad mini rotating but iPad2 devices not rotating. I check the code and find the line : 

Line:1313
if (kLGSideMenuSystemVersion >= 7.0)
    {
        _savedStatusBarHidden = kLGSideMenuStatusBarHidden;
        _savedStatusBarStyle = kLGSideMenuStatusBarStyle;

        [_rootVC removeFromParentViewController];

        _currentShouldAutorotate = NO;
        _currentPreferredStatusBarHidden = (kLGSideMenuStatusBarHidden || !kLGSideMenuIsLeftViewStatusBarVisible);
        _currentPreferredStatusBarStyle = _leftViewStatusBarStyle;
        _currentPreferredStatusBarUpdateAnimation = _leftViewStatusBarUpdateAnimation;

        _waitingForUpdateStatusBar = YES;

        [self statusBarAppearanceUpdate];
        [self setNeedsStatusBarAppearanceUpdate];
    }

This is the commit : https://github.com/Friend-LGA/LGSideMenuController/commit/ea8788878113c48ae780353a668c4162f4a5c67d

but I don't understand why if iOS7 and above shouldn't rotate? 

Thanks.

**Comment by Coledunsby** [comment]
This issue seems to have been resolved. If you are still having trouble, please let me know.
