### ISSUE TITLE
Error set another rootViewController  "setRootViewController"

### ISSUE THREAD

**Issue by marcelobello** [Friend-LGA/LGSideMenuController#3]
Hello. 

 I'm trying to change the rootViewController after touch some index in my MenuClassViewController, example:

if (indexPath.row == 2) {

   NewViewController * newView = [[NewViewController alloc]init];
   UINavigationController * nav = [[UINavigationController alloc]initWithRootViewController:newView];
   [kMainViewController setRootViewController:newView];
}

This step it's ok, but if I try open the Menu again my application stop with this error:

Thread 1: EXC_BAD_ACCESS(code=1, address=0x10)

And showed some problem in this Method: 

- (void)colorsInvalidate
{...}

![screen shot 2015-07-26 at 11 40 10 pm](https://cloud.githubusercontent.com/assets/1929104/8899979/b56c93ae-33ef-11e5-8b46-848d9eb43ba4.png)

 Do you have any idea about that?

Thank you.

**Comment by Friend-LGA** [comment]
Yes, I have.
Probably somewhere you assign
```objective-c
_rootVC = kMainViewController.rootViewController;
```
After change
```objective-c
[kMainViewController setRootViewController:newView];
```
You need to reassign _rootVC
```objective-c
_rootVC = kMainViewController.rootViewController;
```

**Comment by marcelobello** [comment]
Hi.
 
Yes I made it, look:

UIViewController *newViewController = [UIViewController new];

        UINavigationController * nav = [[UINavigationController alloc]initWithRootViewController:newViewController];

        [kMainViewController setRootViewController:nav];

=======================================================

If you look inside this method setRootViewController:


- (void)setRootViewController:(UIViewController *)rootViewController
{
    if (rootViewController)
    {
        if (_rootVC)
        {
            [_rootVC.view removeFromSuperview];
            [_rootVC removeFromParentViewController];
        }
        
//****Here your code reassign the _rootVC.
        _rootVC = rootViewController;
        
        [self addChildViewController:_rootVC];
        [self.view addSubview:_rootVC.view];
        
        // -----
        
        [self rootViewLayoutInvalidateWithPercentage:(self.isLeftViewShowing || self.isRightViewShowing ? 1.f : 0.f)];
    }
}

Doesn't work yet.

Thanks

**Comment by Friend-LGA** [comment]
Make you navigation controller strong variable:
```objective-c
@property(strong, nonatomic) UINavigationController * nav;
...
...
UIViewController *newViewController = [UIViewController new];

self.nav = [[UINavigationController alloc]initWithRootViewController:newViewController];

[kMainViewController setRootViewController:nav];
```

I will try to fix it later

**Comment by Friend-LGA** [comment]
Now is everything ok?

**Comment by marcelobello** [comment]
Perfect! The version 1.0.2 it's ok now.

Thank you so much. ;)

**Comment by Friend-LGA** [comment]
:+1:
