### ISSUE TITLE
TapGesture not working on RootView

### ISSUE THREAD

**Issue by akshaypakanati** [Friend-LGA/LGSideMenuController#31]
@Friend-LGA  

By adding this line at Fixes this problem for left view

        //line no 665
        [self.view bringSubviewToFront:_rootViewCoverViewForLeftView];

**Comment by kevinlin505** [comment]
Please add this. Also, once the left menu is displayed I am no longer able to interact with the menu button. left menu doesn't close when I click on other menu button.

**Comment by akshaypakanati** [comment]
@kevinlin505  above code fixes the issue..
because when left menu opens you no longer need to interact with menu button. just tap anywhere on root, it'll lead to hide left menu
