### ISSUE TITLE
Starting LGSideViewController directly from storyboard is broken

### ISSUE THREAD

**Issue by osrl** [Friend-LGA/LGSideMenuController#34]
Steps to reproduce:
On Demo Storyboard application:
1) Select Main.storyboard as Main interface (from Deployment Info)
2) Add theese lines below `@implementation MainViewController`  in `MainViewController.h`

```
- (void)viewDidLoad {
    [super viewDidLoad];
    UINavigationController *navigationController = [self.storyboard instantiateViewControllerWithIdentifier:@"NavigationController"];
    self.rootViewController = navigationController;


    [self setupWithPresentationStyle:LGSideMenuPresentationStyleSlideAbove type:0];
}
```

`setupWithPresentationStyle:LGSideMenuPresentationStyleSlideBelow` also doesn't work.

Can you provide information about how to start a SideViewController directly from storyboard?

**Comment by eiros** [comment]
Try to use viewDidAppear. It worked for me.

**Comment by arishanapalli** [comment]
@eiros I have same issue issued the viewDidAppear  

-(void)viewDidAppear:(BOOL)animated{
    [super viewDidAppear:YES];
}

in leftMenuViewController its not working for me.

**Comment by Friend-LGA** [comment]
Try new version, is it ok now?

**Comment by Friend-LGA** [comment]
Feel free to open issue back if you have more questions.
