### ISSUE TITLE
Storyboard Example?

### ISSUE THREAD

**Issue by NitWitStudios** [Friend-LGA/LGSideMenuController#4]
This looks like an awesome and more simplified version of other navigation drawer libraries. I was wondering if you could provide an example using storyboards, since thats a pretty common way for setting up view hierarchies these days.
Thanks!

**Comment by ndmeiri** [comment]
+1

**Comment by robertofrontado** [comment]
+1

**Comment by Friend-LGA** [comment]
I do not closely relative to storyboard. Check this commit if somebody can.
