### ISSUE TITLE
LGSideMenuPresentationStyleSlide Above

### ISSUE THREAD

**Issue by thaoth58** [Friend-LGA/LGSideMenuController#40]
I have a issues with LGSideMenuPresentationStyleSlideAbove.
I can use other styles but not this. After click menu button, my main view is dimmed, but i don't see left menu.

Sorry for my bad english, can you help me?

**Comment by Coledunsby** [comment]
This issue seems to have been resolved. If you are still having trouble, please let me know.

**Comment by aparna1591** [comment]
@thaoth58  Hi, I am facing a similar issue. Did you happen to find a solution for this? Could you please help me with the same?
