### ISSUE TITLE
rootViewController Shadow is gone after replacing rootViewController

### ISSUE THREAD

**Issue by kennyevo** [Friend-LGA/LGSideMenuController#41]
If you replace the rootViewController after initializing the whole thing, the shadow is missing.

At first I initialize the menuController with a navigation controller, and there's a button which replaces the navigationcontroller with an other one, after I've replaced the rootViewController of the LGSideMenuController, the shadow is gone when the left or right side menu is shown.

**Comment by Kiratijuta** [comment]
You have to re-insert the _rootViewStyleView right after you assign the new rootViewController. And if you want the clover colour for the left view, you need to re-insert the _leftViewCoverView as well.

Basically, this is the one that i created, you just call the one below;
- (void)updateShadow
{
    [_rootViewStyleView removeFromSuperview];
    [self.view insertSubview:_rootViewStyleView belowSubview:_rootVC.view];
    
    [_leftViewCoverView removeFromSuperview];
    [self.view insertSubview:_leftViewCoverView aboveSubview:_leftView];
    _leftViewCoverColor = kLGSideMenuCoverColor;
}
* This function was written in the LGSideBarMenu.m

**Comment by vinecole27** [comment]
this issue still exists when replace root view controller
