### ISSUE TITLE
How can I use this MenuController with a UITabbarController?

### ISSUE THREAD

**Issue by wanglianghd** [Friend-LGA/LGSideMenuController#44]

**Comment by eiros** [comment]
Is there any solution?:)

**Comment by wanglianghd** [comment]
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    

    ViewController *viewController = [ViewController new];
    NavigationController *navigationController = [[NavigationController alloc] initWithRootViewController:viewController];
    
    UITabBarController *tabbarController = [[UITabBarController alloc]init];
    tabbarController.viewControllers = @[navigationController];
    
     MainViewController *mainViewController = [[MainViewController alloc] initWithRootViewController:tabbarController
                                                              presentationStyle:LGSideMenuPresentationStyleSlideBelow
                                                                           type:0];
    
    self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    self.window.backgroundColor = [UIColor whiteColor];
    self.window.rootViewController = mainViewController;
    [self.window makeKeyAndVisible];
    
    return YES;
}

#define kMainViewController                            (MainViewController *)[UIApplication sharedApplication].delegate.window.rootViewController
#define kTabbarController [(MainViewController *)[UIApplication sharedApplication].delegate.window.rootViewController rootViewController]

// this is the leftViewController
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
        UIViewController *viewController = [UIViewController new];
        viewController.view.backgroundColor = [UIColor whiteColor];
        viewController.title = _titlesArray[indexPath.row];
        UITabBarController *tab = (UITabBarController *)kTabbarController;
        NavigationController *nav = (NavigationController*)tab.viewControllers[0];
        viewController.hidesBottomBarWhenPushed = YES;
        [nav pushViewController:viewController animated:YES];
    
        //  [kNavigationController pushViewController:viewController animated:YES];

        [kMainViewController hideLeftViewAnimated:YES completionHandler:nil];
}

Now I just add one ViewController into UITabbarController.

I can send you a demo to your Email.

**Comment by wanglianghd** [comment]
https://github.com/wanglianghd/WLSideMenuDemo @eiros

**Comment by eiros** [comment]
Thank you! @wanglianghd
