### ISSUE TITLE
Left PanGesture Conflict With NavigationController's POP Gesture When Hidden The NavigationBar !!!

### ISSUE THREAD

**Issue by wanglianghd** [Friend-LGA/LGSideMenuController#45]
![snip20160414_9](https://cloud.githubusercontent.com/assets/7602945/14515209/2ea400dc-022a-11e6-8ce5-b6a4dc6b659a.png)

Like The Picture,I Hidden NavigationBar In ViewController, So The Left PanGesture Conflict With UINavigationController.interactivePopGestureRecognizer When I PushViewController To Next ViewController , How Can Resolve It?

@Friend-LGA Could You Help Me?Thank You Very Much.

**Comment by wanglianghd** [comment]
New Issue:

If I use custom backBarButton to replace the system backBarButton,then the interactivePopGestureRecognizer will Invalid, and the Left PanGesture will be valid.

but we don't need the Left PanGesture when pushed the next viewController,how to resolve it?

**Comment by ideity** [comment]
I'm having the same issues. Any insight would be helpful!

**Comment by wanglianghd** [comment]
@ideity 
If you use custom navigationBar in your project, you can try this method.
when you need hidden the system navigationBar,in the viewWillAppear method, add this code,
[self.navigationController.view sendSubviewToBack:self.navigationController.navigationBar];
and in the viewWillDisappear, add this code,
[self.navigationController.view bringSubviewToFront:self.navigationController.navigationBar];

**Comment by Friend-LGA** [comment]
Try new version, is it ok now?

**Comment by Friend-LGA** [comment]
Feel free to open issue back if you have more questions.
