### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by damirstuhec** [Friend-LGA/LGSideMenuController#47]
Is this project still going to be maintained or not? I see quite a few PRs and Issues not being handled. /cc @Friend-LGA

**Comment by Friend-LGA** [comment]
https://github.com/Friend-LGA/LGSideMenuController/issues/51

**Comment by Coledunsby** [comment]
I will be helping to maintain this project. I will be looking at the PRs and Issues in the coming weeks.

**Comment by Friend-LGA** [comment]
I will make updates sometimes, when I will have free time. It could be rarely. It will be nice to have more collaborators.
