### ISSUE TITLE
addTarget not working

### ISSUE THREAD

**Issue by danielborges93** [Friend-LGA/LGSideMenuController#48]
Hi,

My LeftViewController is a `UIViewController` with `UIButton`s.
In code, I call `addTarget(...)` [in Swift] for a button in LeftView, but it's not working :(

I tried with `@IBOutlet`, but nothing happens.

**Comment by Coledunsby** [comment]
The actions for the buttons should be defined in your `UIViewController` subclass for your LeftViewController. Check out the demo projects for some examples. If you share some code I can point you in the right direction.
