### ISSUE TITLE
.SlideAbove style is not working when used as Left view

### ISSUE THREAD

**Issue by jvanzummeren** [Friend-LGA/LGSideMenuController#53]
.SlideAbove style is not working when used as Left view. When using it as Right view, it's working fine. All  the other styles are working fine.

If you can point me in the right direction i'm also willing to offer a fix in a pull request.

Kind regards

**Comment by Coledunsby** [comment]
This issue seems to have been resolved. If you are still having trouble, please let me know.

**Comment by aparna1591** [comment]
@jvanzummeren , I have an issue where the style isn't working on right menu. Could you please help me ?
