### ISSUE TITLE
How can I push view controller with storyboard identifier?

### ISSUE THREAD

**Issue by sakthikumarmdu** [Friend-LGA/LGSideMenuController#57]
Hi,

I have to push a detail view controller when I tap on a tableview cell using with storyboard identifier. Now i have to navigate to the designed view controller by tap table view cell in the left menu

```
if (indexPath.row == 0) {
    ProfileViewController *profileVC = (ProfileViewController *)[mainStoryboard instantiateViewControllerWithIdentifier:"ProfileVC"];
    [self.leftMenuVC navigateToViewController:profileVC];
}
```

```
- (void)navigateToViewController:(UIViewController *)viewController {
    [(UINavigationController *)[self sideMenuController].rootViewController pushViewController:viewController animated:YES];
    [[self sideMenuController] hideLeftViewAnimated:YES completionHandler:nil];
}
```

**Comment by Coledunsby** [comment]
What issue are you having? Please refer to the demo app. It does what you are describing.

**Comment by sakthikumarmdu** [comment]
They created new view controller while tap the left menu, but i designed separate view controller in storyboard for each menu item. Now i want to navigate to the respective view controller using identifier. But it is not working

**Comment by Friend-LGA** [comment]
Try new version, everything should working fine.
