### ISSUE TITLE
replace root viewcontroller breaks the shadow and gesture

### ISSUE THREAD

**Issue by vinecole27** [Friend-LGA/LGSideMenuController#58]
I added right view and it works fine with first root view controller
but when I replace it, it breaks shadow and tap gesture
I saw the closed issue which is same and the merge fixed this issue but no luck for me
any help is appreciated

**Comment by Coledunsby** [comment]
Are you using the code from the latest commit? I haven't updated the pod spec yet.

**Comment by vinecole27** [comment]
LGSideMenuController (1.0.10)
this is what pod installed

**Comment by Coledunsby** [comment]
I have not created a new version yet including the fix. In the meantime you can include the pod like this to get the latest changes:
```
pod 'LGSideMenuController', :git => 'https://github.com/Friend-LGA/LGSideMenuController.git'
```
I will keep this issue open until I create a new cocoapod release.

**Comment by vinecole27** [comment]
ok, thanks

**Comment by vinecole27** [comment]
@Coledunsby I tried with above pod update but doesn't work

**Comment by Coledunsby** [comment]
I'll have another look

**Comment by vinecole27** [comment]
anything found?

**Comment by vinecole27** [comment]
@Coledunsby I found what caused an issue, line 502 on LGSideMenuController.m should be replaced with 
[self.view insertSubview:_rootViewCoverViewForRightView aboveSubview:_rootViewCoverViewForRightView];

**Comment by vinecole27** [comment]
can you make a quick change and commit?

**Comment by Coledunsby** [comment]
It doesn't make sense to insert the subview above itself. I need some more context about your problem to resolve it. What `LGSideMenuPresentationStyle` are you using? Can you reproduce it in the demo app?

**Comment by vinecole27** [comment]
original line was
[self.view insertSubview:_rootViewCoverViewForRightView aboveSubview:_rootViewCoverViewForLeftView]; which _rootViewCoverViewForLeftView is nil
it should be _rootViewCoverViewForRightView

**Comment by Coledunsby** [comment]
fixed

**Comment by vinecole27** [comment]
thanks

**Comment by vinecole27** [comment]
***I will keep this issue open until I create a new cocoapod release.

I see you closed this issue, have you already updated pod version?

**Comment by murali9** [comment]
Why shadow for right view controller is not coming 

i used the below code.
    self.rootViewLayerBorderColor = [UIColor redColor];
    self.rootViewLayerBorderWidth = 20;

**Comment by murali9** [comment]
Fixed . we have to upgrade to 2.0.4 library
