### ISSUE TITLE
changing root view controller affects status bar

### ISSUE THREAD

**Issue by vinecole27** [Friend-LGA/LGSideMenuController#59]
whenever change root view controller, status is hidden and shown after a sec which looks bad

**Comment by Asich** [comment]
Try this set "LGSideMenuStatusBarVisibleOnAll" on "rightViewStatusBarVisibleOptions" property

**Comment by vinecole27** [comment]
@Asich thanks for advise but this property will make the status bar visible for right side menu  that's not what I want
I need to make the status bar hidden when right side menu is opened and show it again when menu is closed
and this issue happens in this case

**Comment by Friend-LGA** [comment]
Try new version, is it ok now?

Better use UINavigationController as rootViewController for sideMenuController and change viewControllers for this navigationController.

```objective-c
[sideMenuController.rootViewController setViewControllers:@[newViewController]];
```

**Comment by Friend-LGA** [comment]
Feel free to open issue back if you have more questions.
