### ISSUE TITLE
setStatusBarHidden:withAnimation: is deprecated in iOS 9

### ISSUE THREAD

**Issue by ndmeiri** [Friend-LGA/LGSideMenuController#6]
If you plan on supporting iOS 9, please consider removing the deprecated methods used in `LGSideMenuViewController.m`. These following warnings appear when using Xcode 7 beta 4.
![screenshot](https://cloud.githubusercontent.com/assets/8139148/9028807/c971ac6e-3939-11e5-8651-703c05b723da.png)

**Comment by Friend-LGA** [comment]
Ok... I will check it later

**Comment by ndmeiri** [comment]
Thank you very much!

**Comment by ndmeiri** [comment]
Any updates?

**Comment by ninokierulf** [comment]
@ndmeiri why dont you make a pull request?
and this would be a good opportunity to use availability

**Comment by chlebta** [comment]
How to make status bar white ? after adding this library to my project I got status bar black again

**Comment by Friend-LGA** [comment]
You found a bug. I will fix it in few days, and add some new features.

**Comment by Friend-LGA** [comment]
Now it should works fine
