### ISSUE TITLE
Issue after Integrating after login screen application 

### ISSUE THREAD

**Issue by arishanapalli** [Friend-LGA/LGSideMenuController#60]
I integrated LGSideMenuController Removed MainViewControler added MYDashboardViewController  which is added in another storyboard. two storyboard [from login]  then loading LGsideMenu [DashboardViewController],  every things is working perfect expect two things.

1) left menu do have three options (Setting, notification and profile)
When click setting how to make that as my Mainviewcontroller? Do not want to navigate to another viewcontroller.

2) My Dashboardviewcontorller (i.e MainViewController) viewdidload is calling three times.

**Comment by Friend-LGA** [comment]
`sideMenuController.rootViewController = newViewController;`
or
`[sideMenuController.rootViewController pushViewController:newViewController];`
or
`[sideMenuController.rootViewController setViewControllers:@[newViewController]];`

**Comment by Friend-LGA** [comment]
Feel free to open issue back if you have more questions.
