### ISSUE TITLE
i need help with using the lgsidemenucontroller

### ISSUE THREAD

**Issue by ahmadsallam** [Friend-LGA/LGSideMenuController#61]
i have clean project it have only one view,
so i need example how to use LGSideMenuController in clean project please help

**Comment by Friend-LGA** [comment]
Is this demo projects not enough?
* [Objective-C](https://github.com/Friend-LGA/LGSideMenuController/tree/master/Demo_Objective-C)
* [Objective-C + Storyboard](https://github.com/Friend-LGA/LGSideMenuController/tree/master/Demo_Objective-C_Storyboard)
* [Swift](https://github.com/Friend-LGA/LGSideMenuController/tree/master/Demo_Swift)
* [Swift + Storyboard](https://github.com/Friend-LGA/LGSideMenuController/tree/master/Demo_Swift_Storyboard)

**Comment by vamsiprince** [comment]
hi i need help using slide menu i want to load slide menu on button action only

**Comment by Friend-LGA** [comment]
```objective-c
sideMenuController.leftViewSwipeGestureEnabled = NO;
sideMenuController.rightViewSwipeGestureEnabled = NO;
```
