### ISSUE TITLE
How to set LeftMenuItems ViewControllers item to MainViewController

### ISSUE THREAD

**Issue by arishanapalli** [Friend-LGA/LGSideMenuController#63]
Hi
Team,

Your LGSideMenuController is awesome,
But i have a small issue to setting the LeftMenuTableView Items (UIViewController ) to main ViewController,

On leftmenuViewController I have 5 categories (Profile,Setting,Notification,Feedback) this four ViewController i want to set to MainViewController buts here it is navigating to another view controller.

Your feedback is appreciated.

**Comment by Friend-LGA** [comment]
It looks more like bugs in your code, can you show your code?

**Comment by Friend-LGA** [comment]
Feel free to open issue back if you have more questions.
