### ISSUE TITLE
How to change rootviewcontroller in LGSideMenuContorller

### ISSUE THREAD

**Issue by arishanapalli** [Friend-LGA/LGSideMenuController#64]
Hi
Team,

How can i change RootviewController i.e MainViewController to  another Viewcontroller which is coming from leftViewController (i.e TableView ) item.
Is it possible using LGSideMenuController?

**Comment by Friend-LGA** [comment]
`sideMenuController.rootViewController = newViewController;` is not working?

**Comment by Friend-LGA** [comment]
Better use UINavigationController as rootViewController for sideMenuController and change viewControllers for this navigationController.

```objective-c
[sideMenuController.rootViewController setViewControllers:@[newViewController]];
```
