### ISSUE TITLE
How to  performSegueWithIdentifier when click on slider cell

### ISSUE THREAD

**Issue by chiragDJ22** [Friend-LGA/LGSideMenuController#65]
in

> - (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
>   UIViewController *viewController = [UIViewController new];
>       viewController.view.backgroundColor = [UIColor whiteColor];
>       viewController.title = _titlesArray[indexPath.row];
>       [(UINavigationController *)[self sideMenuController].rootViewController pushViewController:viewController animated:YES];
>   [[self sideMenuController] hideLeftViewAnimated:YES completionHandler:nil];
>   }
>   this is create a new viewController it nice but how i open viewController usign  
>   
>   ```
>   [[self sideMenuController] performSegueWithIdentifier:@"identA" sender:nil];
>   ```

 like this if i put in viewController in storyboard ane set segue with identA how i can open that 
viewController

**Comment by Friend-LGA** [comment]
Use UINavigationController as rootViewController for sideMenuController and perform segue as usual. Not on sideMenuController, but on sideMenuController.rootViewController.
