### ISSUE TITLE
Opening side menu using UITabBarController

### ISSUE THREAD

**Issue by RJiryes** [Friend-LGA/LGSideMenuController#7]
Hi, thanks for the great side menu. Is it possible to open the side menu from a UITabBarController from the storyboard demo?

**Comment by safecase123** [comment]
Yes its possible.

<b>Set LGSideMenuController's rootViewController to your UITabBarController's instance.</b>

For example : 

    objLGSideMenuController.rootViewController = [self.storyboard instantiateViewControllerWithIdentifier:@"TabBarVC"];

**Comment by Friend-LGA** [comment]
Yes, like @safecase123 told above, you can use any UIViewController you want, just set it like rootViewController.
Check [MainViewController.m](https://github.com/Friend-LGA/LGSideMenuController/blob/master/Demo%20Storyboard/LGSideMenuControllerDemo/MainViewController.m) in "Demo Storyboard"
You need to change this string:
```objective-c
self.rootViewController = [self.storyboard instantiateViewControllerWithIdentifier:@"NavigationController"];
```
to
```objective-c
self.rootViewController = [self.storyboard instantiateViewControllerWithIdentifier:@"TabBarController"];
```
Ofcourse "TabBarController" suppose to be real UITabBarController in storyboard.

**Comment by RJiryes** [comment]
Thanks! :+1: :+1:

**Comment by ahmedayoub95** [comment]
This popover my view controller but i need to push it so it can have back button or should i add button in that view controller in storyboard and present as .fullscreen?
