### ISSUE TITLE
Wrong width with style slideAbove

### ISSUE THREAD

**Issue by alexsanderkhitev** [Friend-LGA/LGSideMenuController#70]
Hello! We install velechiny 275 points, or any other, in contrast to the width of the screen device, but the left side menu, when the slide occupies the entire width of the screen, how can I fix it? Thanks

```
class SideMenuViewController: LGSideMenuController {

    override func viewDidLoad() {
        super.viewDidLoad()
        setupSideMenu()
    }
  
    private func setupSideMenu() {
        let storyboardManager = StoryboardManager()
        
        setLeftViewEnabledWithWidth(275, presentationStyle: .slideAbove, alwaysVisibleOptions: [])
        
        let leftMenuController = storyboardManager.leftMenu.instantiateViewControllerWithIdentifier(LeftMenuTableViewController.self)
        leftViewStatusBarStyle = .default
        leftViewStatusBarVisibleOptions = .onAll

        leftView().addSubview(leftMenuController.tableView)
    }

}
```

UPDATE
I have tried, this happens only on the left side.

**Comment by Friend-LGA** [comment]
Check value `sideMenuController.leftViewWidth` right before `showLeftView` action. Is it have right value?

**Comment by Friend-LGA** [comment]
Feel free to open issue back if you have more questions.

**Comment by lwinged** [comment]
I have same issue on iPhone 6s plus when I close the left menu. 
the leftview is set to 237 width (leftViewWidth)
On iphone SE there is no issue.

I think width is larger than I set but leftViewWidth et leftViewcontroller.view are right (237).
the leftview doesn't close correctly (see the little border)

![slide above iphone 6s plus](https://cloud.githubusercontent.com/assets/7090742/22242701/a9e9bfb8-e224-11e6-94ac-e0a92bd539dc.png)
![slide above iphone 6s plus bug close left view](https://cloud.githubusercontent.com/assets/7090742/22242702/a9ec5886-e224-11e6-8682-5533b6e2a981.png)

An example with slide below on iphone 6s plus the width is right but not with slideAbove

![slide below](https://cloud.githubusercontent.com/assets/7090742/22242854/352066c2-e225-11e6-80f4-7acd05ebaa62.png)
