### ISSUE TITLE
Unable to import Carthage-built framework into Swift project

### ISSUE THREAD

**Issue by craigotis** [Friend-LGA/LGSideMenuController#71]
I have the following in my Cartfile:
```
github "Friend-LGA/LGSideMenuController" ~> 1.0.10
```
And when I run `carthage update --no-use-binaries --platform iOS` it builds successfully. However when I drag the framework into my project, it looks like the umbrella header has a different name than the framework itself. (The framework ends with `...Framework.framework` which seems unconventional.)
<img width="299" alt="screen shot 2016-11-13 at 10 26 25 am" src="https://cloud.githubusercontent.com/assets/1620098/20246763/0fbaedac-a98c-11e6-9d82-9b974f1fb9d1.png">
This seems to be causing build issues:
<img width="477" alt="screen shot 2016-11-13 at 10 26 18 am" src="https://cloud.githubusercontent.com/assets/1620098/20246765/21cd04a8-a98c-11e6-86ad-502d92eba086.png">
And I'm unable to import the framework into my Swift project. I have 4 other frameworks in my Cartfile that imported without issue.

**Edit:** It looks like the `module.modulemap` file also refers to a `...Framework.h` header file, but this is not present in the built framework - only `LGSideMenuController.h` exists:
```
framework module LGSideMenuControllerFramework {
  umbrella header "LGSideMenuControllerFramework.h"

  export *
  module * { export * }
}
```

**Comment by Friend-LGA** [comment]
Fixed
