### ISSUE TITLE
Right menu shown and wrong layout

### ISSUE THREAD

**Issue by Reggionick** [Friend-LGA/LGSideMenuController#73]
Hi, I think that I've found a bug in the layout handling: the rootViewController's view is resized and the rightView is shown on the right side also if it should not.
The issue is reproducible also in the Demo_Objective-C_Storyboard Project with an iPad on iOS 10.

These are the steps to reproduce the issue:

1. Rotate the device in portrait position
2. Open the right menu
3. Select a menu item while rotating the device in landscape position

![issue_reproduced](https://cloud.githubusercontent.com/assets/4193249/20930055/73dc8a1e-bbcc-11e6-8ca1-465d4c20f675.PNG)

Have you a suggestion on how to fix it?
Thanks

**Comment by Friend-LGA** [comment]
Right now I am working on new version. It will be done in few days. I will try to fix it.

**Comment by Friend-LGA** [comment]
Try new version, is it ok now?

**Comment by Reggionick** [comment]
No, the issue is still reproducible..

**Comment by Friend-LGA** [comment]
I can't reproduce it. When any of side menus is opened, rotation is disabled because rootViewController removed from it's parent view controller and rotation can cause some visual bugs.
Can you capture video using for example QuickTime player?

**Comment by Reggionick** [comment]
Sure! [Here](https://www.dropbox.com/s/jz0p7x2usa6bomi/Issue_%2373-480.mov?dl=1) you can download the video.

**Comment by Friend-LGA** [comment]
Since iOS 9.0, if multitasking for iPad is enabled, we can't control autorotation.
I fix it, now you can rotate device even when side views is showing.
Try new version (2.0.2)

**Comment by Reggionick** [comment]
Yes! Issue fixed!
Thanks

**Comment by Friend-LGA** [comment]
You are welcome :)
