### ISSUE TITLE
LGSideMenuController + UINavigationController

### ISSUE THREAD

**Issue by ulian-onua** [Friend-LGA/LGSideMenuController#74]
I use LGSideMenuController and set of UINavigationControllers with embedded view controllers as a every menu position.
I can't back to previous view controller in navigation stack by swiping left so as pan gesture of LGSideMenuController is active.
How can it be possible to use swipe to back in navigation stack?
I've tried these commands but they didn't solve my problem:
self.sideMenuController.leftViewSwipeGestureEnabled = NO;     self.sideMenuController.rightViewSwipeGestureEnabled = NO;
self.sideMenuController.gesturesCancelsTouchesInView = NO;

**Comment by Friend-LGA** [comment]
Just check demo projects. If you will open any of side views and will tap on some cell, then new view controller will be pushed into navigation stack and back gesture will work as expected.

**Comment by Friend-LGA** [comment]
Feel free to open issue back if you have more questions.
