### ISSUE TITLE
Storyboard Demo doesn't work properly on iPad (real device). Menu is white.

### ISSUE THREAD

**Issue by ulian-onua** [Friend-LGA/LGSideMenuController#75]
Hello. Storyboard Demo doesn't work properly on iPad (real device - iPad Pro 9.7, iOS 9). Menu is white after opening. iPad Simulator works well.
I've tried your new version of LGSideMenuController in my proprietary project and it also showed me white menu(
Please help with this problem.
![img_0217](https://cloud.githubusercontent.com/assets/15073398/21311819/e29865a2-c5f1-11e6-8e19-eb5d7c5ae122.PNG)
![img_0218](https://cloud.githubusercontent.com/assets/15073398/21311820/e29b40f6-c5f1-11e6-8fe6-882923222b94.PNG)

**Comment by Friend-LGA** [comment]
Prior iOS 10, you need to programmatically set clear background for UITableViewCell.
I updated demo projects, you can download new version.

**Comment by ulian-onua** [comment]
Thank you! Now everything works excellent!
