### ISSUE TITLE
When switching the rootViewController out all of the views double in size

### ISSUE THREAD

**Issue by james-ff** [Friend-LGA/LGSideMenuController#76]
I have just updated my copy of this library from the version it was back in August and I'm getting a strange bug where all of the content views in my view hierarchy are double in size. I'm not sure if it is being caused by this library as I did update a few others (but none of them would or should have an effect on the view hierarchy), I'm interested though to see if you or anyone else has come across this?
*screenshot attached
![simulator screen shot 20 dec 2016 20 34 08](https://cloud.githubusercontent.com/assets/1874352/21368483/adb08982-c6fa-11e6-9165-499a00b23516.png)
*

**Comment by Friend-LGA** [comment]
You need to override method `rootViewWillLayoutSubviewsWithSize:`
Something like that:
```
- (void)rootViewWillLayoutSubviewsWithSize:(CGSize)size {
    self.rootView.frame = CGRectMake(0.0, 0.0, size.width, size.height);
}
```
Or you can add constraints to it's superview

**Comment by james-ff** [comment]
This fixed it! Thanks for the rapid response!

**Comment by Friend-LGA** [comment]
You are welcome :)
