### ISSUE TITLE
Show Menu button in Child Vewcontroller

### ISSUE THREAD

**Issue by mgurnani** [Friend-LGA/LGSideMenuController#77]
Hello,

I am trying to use this in a Swift project. It is really an awesome library!!

I have one question: Take example of Demo Swift project only ("Scale From Big Style"). If I select "Profile" or "News", it shows a Back navigation to LGSideMenuVC.. Instead I want to display the Menu button in Nav bar on these views controllers also. Can you suggest how should I go about it ?

Thanks in advance !

**Comment by Friend-LGA** [comment]
You need to read documentation:
* https://developer.apple.com/reference/uikit/uinavigationcontroller
* https://developer.apple.com/reference/uikit/uinavigationbar
* https://developer.apple.com/reference/uikit/uinavigationitem

**Comment by ibhavin** [comment]
@Friend-LGA  Can you show set up of storyboard to display menu button instead of back button for "Profile" or "News"? It will be really helpful.

**Comment by ibhavin** [comment]
@mgurnani Have you find the answer? How did you do that?

**Comment by iDevelopper** [comment]
Just create a ProfileViewController and replace the root view controller by it instead of pushing it with a navigation controller. See In Demo -> Swift_Storyboard Example I modified.

```
        else if indexPath.row == 4 { // Profile
            let navigationController = mainViewController.rootViewController as! NavigationController
            let viewController: UIViewController!
            
            viewController = self.storyboard!.instantiateViewController(withIdentifier: "ProfileViewController")
            
            navigationController.setViewControllers([viewController], animated: false)

            mainViewController.hideLeftView(animated: true, delay: 0.0, completionHandler: nil)
        }
```

[LGSideMenuController-master-3.zip](https://github.com/Friend-LGA/LGSideMenuController/files/1780179/LGSideMenuController-master-3.zip)
