### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by iDhaval** [Friend-LGA/LGSideMenuController#78]
Using with cocoapods

`[LGSideMenuController sideMenuControllerWithRootViewController:navigationController
                                                                                       leftViewController:leftViewController
                                                                                      rightViewController:rightViewController];`

**Comment by Friend-LGA** [comment]
I checked it right now, everything is working fine

```objective-c
//  ViewController.m

#import "ViewController.h"

@import LGSideMenuController;

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];

    LGSideMenuController *sideMenuController = [LGSideMenuController sideMenuControllerWithRootViewController:nil leftViewController:nil rightViewController:nil];
}

@end
```
