### ISSUE TITLE
Missing parentViewController

### ISSUE THREAD

**Issue by bernikowich-cedoni** [Friend-LGA/LGSideMenuController#80]
After opening and closing side menus with pan gesture parentViewController of rootViewController is nil.

**Comment by Friend-LGA** [comment]
I checked it right now and everything is fine.
In demo project you can add something like this to try it by yourself:
```objective-c
// ViewController.m

- (void)viewDidLoad {
    [super viewDidLoad];

    [NSTimer scheduledTimerWithTimeInterval:5.0 repeats:YES block:^(NSTimer * _Nonnull timer) {
        NSLog(@"%@", self.navigationController.parentViewController);
    }];
}
```
`rootViewController` remove from it's `parentViewController` only while any of side views is in opening process. After side view would open, `rootViewController` became again `childViewController` of `sideMenuController`. You can either use property `sideMenuController`, like `rootViewController.sideMenuController`, to get `sideMenuController` any time, when side view is hidden or showing or it is in transition process.

If issue is still reproduced, give me more info:
* Do you use carthage or cocoapods
* iPhone or iPad
* iOS version

And write steps to I can reproduce this issue in demo project using simulator.
