### ISSUE TITLE
Right to left languages

### ISSUE THREAD

**Issue by rabehssera** [Friend-LGA/LGSideMenuController#81]
Hello

I'm working on an app that should work in 2 languages. One is a left-to-right language, the other one a right-to-left language.
It seems like the library is stopping my app to do the layout correctly. Any idea why ?

**Comment by Friend-LGA** [comment]
Hard to imagine how this library can affect on translations. You create layouts for your controllers by yourself and LGSideMenuController use it without any changes.
Can you provide some examples or demo project?

**Comment by rabehssera** [comment]
Well, I managed to have the right layout... Except that the left menu stays on the left (I want it to go on right for the right to left languages)...

**Comment by Friend-LGA** [comment]
Then you need to check current language and choose left or right side to show your menu. You need to do it manually.

**Comment by bernikowich-cedoni** [comment]
You should do it yourself or you can create subclass/category with leading/trailing properties.
