### ISSUE TITLE
Whats the behavior of the side menu if Views are flipped to RTL

### ISSUE THREAD

**Issue by MoazHussam** [Friend-LGA/LGSideMenuController#86]
Hi,

I want to know how the library will behave in case all views are RTL flipped by the system for RTL languages. Does the right view become left and so on?

**Comment by Friend-LGA** [comment]
No, you need to change it manually. I think it is not responsibility of this library. Often you do not need to change left and right views even for RTL languages. RTL words can be shown in the same places as LTR.
