### ISSUE TITLE
 Crash in iOS 9 Devices. LGSideMenuController.m line 1210 -[LGSideMenuController setRootViewController:]

### ISSUE THREAD

**Issue by alokvnair** [Friend-LGA/LGSideMenuController#87]
Hi,

An app I developed is crashing on iOS 9.0 devices in LGSideMenuController.m line 1210 -[LGSideMenuController setRootViewController:].

Any idea on why this is occurring? I am not able to reproduce this on my end in simulator. But I got several crash logs in Crashlytics, and the numbers are high. Any help or suggestions would be appreciated. The app is live in AppStore and needs urgent fix for this issue. Thanks in advance.

Added full crash log below:

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1976a5bdc objc_msgSend + 28
1  UIKit                          0x18865bfb4 -[UINibStringIDTable lookupKey:identifier:] + 132
2  UIKit                          0x188657c04 -[UINibDecoder decodeObjectForKey:] + 48
3  UIKit                          0x1885399e4 -[UIProxyObject initWithCoder:] + 104
4  UIKit                          0x188657fdc UINibDecoderDecodeObjectForValue + 672
5  UIKit                          0x188657d24 -[UINibDecoder decodeObjectForKey:] + 336
6  UIKit                          0x188539c38 -[UIRuntimeConnection initWithCoder:] + 188
7  UIKit                          0x18853a3d8 -[UIRuntimeEventConnection initWithCoder:] + 68
8  UIKit                          0x188657fdc UINibDecoderDecodeObjectForValue + 672
9  UIKit                          0x188658154 UINibDecoderDecodeObjectForValue + 1048
10 UIKit                          0x188657d24 -[UINibDecoder decodeObjectForKey:] + 336
11 UIKit                          0x188538f6c -[UINib instantiateWithOwner:options:] + 1220
12 UIKit                          0x1883e414c -[UIViewController _loadViewFromNibNamed:bundle:] + 376
13 UIKit                          0x1881b049c -[UIViewController loadView] + 176
14 UIKit                          0x188073d44 -[UIViewController loadViewIfRequired] + 144
15 UIKit                          0x188073c9c -[UIViewController view] + 28
16 *******                       **0x100100204 -[LGSideMenuController setRootViewController:] (LGSideMenuController.m:1210)**
17 *******                       0x10046da74 LoginViewController.(loginAction() -> ()).(closure #1) (MainViewController.swift:36)
18 Alamofire                      0x100e757b8 specialized DataRequest.(response<A where ...> (queue : DispatchQueue?, responseSerializer : A, completionHandler : (DataResponse<A.SerializedObject>) -> ()) -> Self).(closure #1).(closure #1) (ResponseSerialization.swift)
19 libdispatch.dylib              0x197eb16e8 _dispatch_call_block_and_release + 24
20 libdispatch.dylib              0x197eb16a8 _dispatch_client_callout + 16
21 libdispatch.dylib              0x197eb6db0 _dispatch_main_queue_callback_4CF + 1844
22 CoreFoundation                 0x182a981f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
23 CoreFoundation                 0x182a96060 __CFRunLoopRun + 1628
24 CoreFoundation                 0x1829c4ca0 CFRunLoopRunSpecific + 384
25 GraphicsServices               0x18dc00088 GSEventRunModal + 180
26 UIKit                          0x1880dcffc UIApplicationMain + 204
27 *********                       0x10011e0dc main (AppDelegate.swift:20)
28 libdyld.dylib                  0x197ee28b8 start + 4

**Comment by iDevelopper** [comment]
I already told you I did not think it came from the library.

https://github.com/John-Lluch/SWRevealViewController/issues/674#issuecomment-276003088

**Comment by alokvnair** [comment]
@iDevelopper If the crash is because of usage of any new methods available since iOS 10, then it should crash on iOS8 devices also, which is not happening. The crash is happening only in iOS 9 devices. The issue which you linked is for SWRevealViewController and I removed it and used LGSideMenuController. I have implemented the logic same like in the sample using Storyboard.

**Comment by iDevelopper** [comment]
If it does not crash on iOS8, you are right. But if it crash with the two librairies, then the problem comes from elsewhere, no? I have tested your application on my iPad 9.

**Comment by alokvnair** [comment]
@iDevelopper Is it crashing on your iPad?

**Comment by iDevelopper** [comment]
The first time I try it some days ago, no. And now yes, at launch I can see a white screen during few seconds ans it crash. iPad mini iOS 9.3.2.

**Comment by Friend-LGA** [comment]
I think this issue is not a problem of the library. Probably you have some errors in your own code.
