### ISSUE TITLE
UIVisualEffectView alpha = 0 issue

### ISSUE THREAD

**Issue by mlagzdins** [Friend-LGA/LGSideMenuController#88]
Hello.
I'm having an issue with this Library in iOS 9.
After initialising the library, when it sets the rootViewController, it logs into console this:

> <UIVisualEffectView 0x15eb1ba0> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

The way, how I am initialising the LGSideMenuController:

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions:[UIApplicationLaunchOptionsKey: Any]?) -> Bool {
 
     let c = LGSideMenuController.init(rootViewController: window!.rootViewController)
     window!.rootViewController = c

     return true
}
```

Warning is logged from last ELSE case from LGSideMenuController.m (line 1764)

```
if (self.leftView && self.isLeftViewVisible) {
        self.rootViewCoverView.alpha = self.rootViewCoverAlphaForLeftView * percentage;
    }
    else if (self.rightView && self.isRightViewVisible) {
        self.rootViewCoverView.alpha = self.rootViewCoverAlphaForRightView * percentage;
    }
    else {
        self.rootViewCoverView.alpha = percentage;
    }
```

How can I prevent the app from logging this / or fix this issue?

I am using XCode Version 8.2.1 (8C1002), Swift 3.0, app support starts with iOS 9.0, LGSideMenuController 2.0.5

**Comment by Friend-LGA** [comment]
I will try to fix it soon.

**Comment by mlagzdins** [comment]
Thank you very much! I appreciate your caring!

**Comment by PabloRueda** [comment]
Same problem here :(

**Comment by Friend-LGA** [comment]
Ok, I spend a lot of time trying figure out how to fix it, but it seems that there is no any way to achieve this. Many people have the same problem in different other cases and frameworks.
But this warning really just a warning, it is not dangerous and you can simply ignore it.
