### ISSUE TITLE
Round corners on rootView

### ISSUE THREAD

**Issue by remyayad** [Friend-LGA/LGSideMenuController#89]
I would like to add round corners to the root view ONLY when the LeftViewController is showing (see attachment 1). I've been advised to use : 

`sideMenuController.rootViewContainer.layer.cornerRadius = 8.0` which didn't do anything.

I tried using the following code instead and the result was half way of what was desired (see attachments 2 & 3) : 

`rootViewContainer?.cornerRadius = 8.0`

Issues : 
- The round corners appear on the root view even when no side-menu is showing
- When we expand the side-menu, we see a black BG behind the rounded corners

If this could be fixed, it would be great. 
Thank you!

![attachment1](https://cloud.githubusercontent.com/assets/22631216/23111221/1c185c18-f6f5-11e6-8b3b-24c1a96f5c50.jpg)
![attachment2](https://cloud.githubusercontent.com/assets/22631216/23111222/1c1924e0-f6f5-11e6-8cb5-52650f0304da.png)
![attachment3](https://cloud.githubusercontent.com/assets/22631216/23111223/1c195e10-f6f5-11e6-8641-17cb61c58de8.png)

**Comment by Friend-LGA** [comment]
I tried to implement this feature. But it has really bad performance.
You can check it out by yourself in this branch:
[test_rounded_corners](https://github.com/Friend-LGA/LGSideMenuController/compare/test_rounded_corners)

If you will have any ideas, pull requests are welcome.
