### ISSUE TITLE
Tableview not visible anymore after setting background image

### ISSUE THREAD

**Issue by kentim** [Friend-LGA/LGSideMenuController#9]
Hi,

After setting the backgroundimage the tableview isn't visible anymore.. If I remove the backgroundimage I can see it, but when I set the backgroundimage I only see the image..

I've tried adding it after adding the tableview as a subview, before etc etc. nothing...

Any idea what that can be?

(it's in Swift)

var rootvc = self.storyboard?.instantiateViewControllerWithIdentifier("ViewController") as! ViewController;
        rightMenu = self.storyboard?.instantiateViewControllerWithIdentifier("RightViewController") as! RightViewController;
        
        self.setRootViewController(rootvc);
        self.rightViewBackgroundImage = UIImage(named: "ocean");
        
        self.setRightViewEnabledWithWidth(100.0, presentationStyle: LGSideMenuPresentationStyleScaleFromBig, alwaysVisibleOptions: LGSideMenuAlwaysVisibleOnNone);
        //self.rightViewBackgroundImage = UIImage(named: "ocean.jpg");
        
        rightMenu.tableView.reloadData();
        rightMenu.tableView.backgroundColor = UIColor.clearColor();
        
        var rightView = self.rightView();
        
        rightView.addSubview(rightMenu.tableView)
        
        rootvc.main = self;

**Comment by Friend-LGA** [comment]
Check out demo projects, it shows how to use LGSideMenuController with tableViews and backgroundImages.

Your code looks not bad. But this line is a little strange ```rootvc.main = self;``` I think you don't need this.
And use this method to set frame for your tableView:
```objective-c
- (void)leftViewWillLayoutSubviewsWithSize:(CGSize)size;
```
