### ISSUE TITLE
Code creates XCode errors

### ISSUE THREAD

**Issue by remyayad** [Friend-LGA/LGSideMenuController#90]
The following code (in LeftViewCell and RightViewCell) which highlights the table items when clicked creates XCode errors : 

`override func setHighlighted(_ highlighted: Bool, animated: Bool) {
    titleLabel.alpha = highlighted ? 0.5 : 1.0
}`

These errors do not prevent the project from running (yes they are errors not warnings). For now, I keep these sections of code commented in both LeftViewCell and RightViewCell, but as soon as I uncomment one of them (or both), I get the following errors : 

<img width="288" alt="screen shot 2017-02-19 at 11 04 15 pm" src="https://cloud.githubusercontent.com/assets/22631216/23111618/c70d1ac6-f6f7-11e6-98a3-85a56ee8b61f.png">

**Comment by Friend-LGA** [comment]
This code is not part of framework, it is part of demo projects, actually you don't need to use it. But really no one of demo projects is not generating errors like this. I think problem inside your own code.

I hope you are using latest version of Xcode.
