### ISSUE TITLE
Port of LGSideViewController to Xamarin iOS and Xamarin Forms

### ISSUE THREAD

**Issue by YahavGB** [Friend-LGA/LGSideMenuController#91]
Hi!

First things first, you've done a wonderful job at this project!

I really liked this project and wanted to integrate it in my project, however since I'm developing a cross platform project using Xamarin iOS and Xamarin Forms - I couldn't use it in its current state. Therefore, I took the glove and created a bindable Xamarin iOS library, as well as a minimal Xamarin Forms implementation.

I thought I should post a link to the repository here, in case somebody else is looking into integrating this library into his/her Xamarin iOS/Forms project. 

The repository link: https://github.com/yahavgb/LGSideMenuController-Xamarin .

Thanks again and well done.

**Comment by Friend-LGA** [comment]
Thank you for Xamarin port. I added info about your repository to README.
