### ISSUE TITLE
Bug NavController in TabController

### ISSUE THREAD

**Issue by Arnoymous** [Friend-LGA/LGSideMenuController#92]
since 2.0.6 when i use a navcontroller in a tabcontroller all animations fails with a warning 

> Unbalanced calls to begin/end appearance transitions for ...

exemple to reproduce : 

      class MainController: LGSideMenuController {
           override func viewDidLoad() {
                super.viewDidLoad()
        
                let a = UIViewController()
                a.title = "root"
                a.view.backgroundColor = .red
        
                let b = UIViewController()
                b.title = "push"
                b.view.backgroundColor = .blue
        
                let nav = UINavigationController(rootViewController: a)
        
                let tab = UITabBarController()
                tab.setViewControllers([nav], animated: false)
        
                self.rootViewController = tab
        
                Async.main(after: 2) {
                    nav.pushViewController(b, animated: true)
                }
            }
      }

**Comment by Arnoymous** [comment]
if it can help, it can be fixed by setting the rootViewController in viewDidAppear

**Comment by Friend-LGA** [comment]
I checked it with a little bit different code and everything is fine...

TableViewController.swift
Change only function `override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)`
```swift
override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let mainViewController = MainViewController()

        let window = UIApplication.shared.delegate!.window!!
        window.rootViewController = mainViewController

        UIView.transition(with: window, duration: 0.3, options: [.transitionCrossDissolve], animations: nil, completion: nil)
    }
```

MainViewController.swift
Replace it all
```swift
class MainViewController: LGSideMenuController {
    override func viewDidLoad() {
        super.viewDidLoad()

        let a = UIViewController()
        a.title = "root"
        a.view.backgroundColor = .red

        let b = UIViewController()
        b.title = "push"
        b.view.backgroundColor = .blue

        let nav = UINavigationController(rootViewController: a)

        let tab = UITabBarController()
        tab.setViewControllers([nav], animated: false)

        self.rootViewController = tab

        DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) {
            nav.pushViewController(b, animated: true)
        }
    }
}
```

**Comment by Arnoymous** [comment]
you can pop interactively the navcontroller ? 
when i do this it pop non interactively and i've a warning with 

> Unbalanced calls to begin/end appearance transitions for <UIViewController: 0x7fd147224600>.

and i don't know why but when i use rootView = tab.view
the rootView frame is set to 2x my screen size

**Comment by Arnoymous** [comment]
strange in a new project i don't have bug..
I will look deeper

**Comment by Friend-LGA** [comment]
Yes, I can pop navigation controller interactively.

Checkout branch "test_tab_controller_warning" and test it by yourself

**Comment by Arnoymous** [comment]
can you try on https://github.com/Arnoymous/LGSideMenuControllerBug please ? @Friend-LGA 
change the Podfile.lock in 2.0.5 after trying in 2.0.8 and see :)

**Comment by Arnoymous** [comment]
If the LGSideMenuController is in a NavController then, the bug is visible (after 2.0.5)

**Comment by Friend-LGA** [comment]
You do it in wrong way. I fixed your project, check it out: [LGSideMenuControllerBug](https://www.dropbox.com/s/8l3cbw5vcwtlkvl/LGSideMenuControllerBug.zip?dl=0)

**Comment by Arnoymous** [comment]
@Friend-LGA Actually in my application I need the LGSideMenuController in a NavController because it's not my rootViewController.
If have a kind of master loader view who can push on my LGSideMenuController or others controller

**Comment by Friend-LGA** [comment]
Check this: [LGSideMenuControllerBug2](https://www.dropbox.com/s/gykzj1bc3hp6f6l/LGSideMenuControllerBug2.zip?dl=0)

**Comment by Arnoymous** [comment]
@Friend-LGA yeah but there is no TabController in the LGSideMenuController and no NavController in the TabController, it's the bug

you need to add this code in the ViewController.swift
`        self.isLeftViewSwipeGestureEnabled = false
        
        let a = UIViewController()
        a.title = "root"
        a.view.backgroundColor = .red
        
        let b = UIViewController()
        b.title = "push"
        b.view.backgroundColor = .blue
        
        let nav = UINavigationController(rootViewController: a)
        
        let tab = UITabBarController()
        tab.setViewControllers([nav], animated: false)
        
        self.rootViewController = tab
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) {
            nav.pushViewController(b, animated: true)
        }`

**Comment by Arnoymous** [comment]
And remove the custom seg in storyboard for rootViewController @Friend-LGA

**Comment by Arnoymous** [comment]
@Friend-LGA And then edit the Podfile.lock, downgrade to 2.0.5 and see there is no bug anymore

**Comment by Friend-LGA** [comment]
Yeah, you were right, I found the bug. I will try to fix it soon. Thank you.

**Comment by Arnoymous** [comment]
Thx !! :)
