### ISSUE TITLE
Can't get the "side menu" segue 

### ISSUE THREAD

**Issue by greenzeal** [Friend-LGA/LGSideMenuController#93]
Hi!

thanks fog good side menu!
want to use it with segues, but can't get the "side menu" segue when connecting the MainViewController with LeftViewController.

in example it presented:
![screen shot 2017-03-29 at 11 46 40 pm](https://cloud.githubusercontent.com/assets/7046543/24473346/fea4d514-14d9-11e7-9e9e-acef5c6dbe01.png)

thanks in advance!

**Comment by Friend-LGA** [comment]
* How do you integrate library to your project? Copy-Paste, Carthage, CocoaPods?
* What version of Xcode?
* Objective-C or Swift?

**Comment by iAviatorJose** [comment]
Kindly provide more info.

**Comment by greenzeal** [comment]
Sorry for less details. Just another day found out that LGSideMenuSegue is not included in pods. I just imported framework manually. 

Thanks again for good library!
