### ISSUE TITLE
Container Blank Space

### ISSUE THREAD

**Issue by Qianen1111** [Friend-LGA/LGSideMenuController#95]
Hello, 

When setting a navigation controller as the root view controller, I get an empty space near the bottom.

![screen shot 2017-04-03 at 11 19 21 pm](https://cloud.githubusercontent.com/assets/23658169/24640749/8eb77c9c-18c7-11e7-9fe0-d1edd948c9ad.png)
![screen shot 2017-04-03 at 11 10 51 pm](https://cloud.githubusercontent.com/assets/23658169/24640748/8eb73598-18c7-11e7-88d6-2949b7f75103.png)

Thanks,
Qianen

**Comment by Friend-LGA** [comment]
Try to create test empty project and if issue will reproduce, share this project here

**Comment by TouchFriend** [comment]
I write a project ,i add a panGesture to rootView,my leftsideView's tableview can't touch ,why?,like 
"gesture area full screen" demo

**Comment by Friend-LGA** [comment]
@Qianen1111 If you create demo project feel free to reopen issue
