### ISSUE TITLE
Swipe gesture on TableViewCell most of times doesn't work

### ISSUE THREAD

**Issue by navern** [Friend-LGA/LGSideMenuController#97]
I noticed that swipe gesture doesn't work (2.0.9). Actually it works, but only if I swipe very fast. Normal slow panning always fails. I have a table in my root view and a menu in the left. Swipe area is LGSideMenuSwipeGestureAreaFull.
I noticed that @zmian solution from this commit (https://github.com/zmian/LGSideMenuController/commit/0884d90d8ec9cff8ca991a5df4e14c3ed5ab4020) works perfectly (need only last part of it). I added delegate method **shouldRequireFailureOfGestureRecognizer** right to **LGSideMenuControllerGesturesHandler** and it worked.
Please confirm someone, maybe I'm doing wrong.

**Comment by Friend-LGA** [comment]
Look at demo project -> Editable table view

You need to use `LGSideMenuSwipeGestureAreaBorders` and then other swipe gestures will work at the centre of the screen as expected. You can use this option only on view controller that need it.

For example:
```objective-c
#import "UIViewController+LGSideMenuController.h"

...

-  (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];

    self.sideMenuController.swipeGestureArea = LGSideMenuSwipeGestureAreaBorders;
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];

    self.sideMenuController.swipeGestureArea = LGSideMenuSwipeGestureAreaFull;
}
```

**Comment by navern** [comment]
Yes, but solution with shouldRequireFailureOfGestureRecognizer may be acceptable to people who want to use the full area to show side menu.

**Comment by Friend-LGA** [comment]
You have full access to `UIPanGestureRecognizer` as `sideMenuController.panGesture` and can set `shouldRequireFailureOfGestureRecognizer` if you want it.
