### ISSUE TITLE
Status bar is not hide neither for leftViewController nor for rootController.

### ISSUE THREAD

**Issue by fasteroko** [Friend-LGA/LGSideMenuController#98]
A few weeks ago i used this combination in LGSideMenuController instance to set status bar hidden for left menu with animation, and return it for root controller:

    self.leftViewWidth = 250.0;
    self.leftViewPresentationStyle = LGSideMenuPresentationStyleSlideAbove;
    
    self.rootViewStatusBarHidden = NO;
    self.rootViewStatusBarUpdateAnimation = UIStatusBarAnimationFade;

    self.leftViewStatusBarHidden = YES;
    self.leftViewStatusBarUpdateAnimation = UIStatusBarAnimationFade;

But now it is not works. What happens? 
Thank you for answer, Vladyslav.

**Comment by Friend-LGA** [comment]
I have just checked it with latest version 2.0.10 and it seems working fine.

Try to check, is everything working as expected in demo projects? If it is, then I think problem can be inside code that you added in the last few weeks.
And you can make one more experiment: create a new fresh project and test how it will work there.
