### ISSUE TITLE
Display freezes when gesture canceled

### ISSUE THREAD

**Issue by donhuff** [Friend-LGA/LGSideMenuController#99]
Reproduce:
1. Set a left view to display under the root view.
2. Start a pan gesture by dragging from the upper left corner toward the center of the screen.
3. When this pan gesture also pulls down the iOS Notification Center, the pan gesture is canceled in the app. This freezes the app in the "left view is opening" state and no more gesture messages are delivered.

**Comment by donhuff** [comment]
@Friend-LGA thanks for merging this in. Great library, btw!

**Comment by Friend-LGA** [comment]
@donhuff thanks for participating :)
